/*
 * JSP generated by Resin Professional 4.0.36 (built Fri, 26 Apr 2013 03:33:09 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import CP_Classes.User;
import CP_Classes.vo.voUser;
import CP_Classes.vo.voUserDemographic;
import CP_Classes.vo.voJobFunction;
import CP_Classes.vo.voJobLevel;
import CP_Classes.vo.voGender;
import CP_Classes.vo.voAge;
import CP_Classes.vo.voEthnic;
import CP_Classes.vo.voLocation;
import java.util.Vector;
import CP_Classes.PrelimQuestion;

public class _demographicentry__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");
    response.setCharacterEncoding("utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string1, 0, _jsp_string1.length);
    CP_Classes.Database Database;
    synchronized (pageContext.getSession()) {
      Database = (CP_Classes.Database) pageContext.getSession().getAttribute("Database");
      if (Database == null) {
        Database = new CP_Classes.Database();
        pageContext.getSession().setAttribute("Database", Database);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.DemographicEntry DemographicEntry;
    synchronized (pageContext.getSession()) {
      DemographicEntry = (CP_Classes.DemographicEntry) pageContext.getSession().getAttribute("DemographicEntry");
      if (DemographicEntry == null) {
        DemographicEntry = new CP_Classes.DemographicEntry();
        pageContext.getSession().setAttribute("DemographicEntry", DemographicEntry);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.RatersDataEntry RDE;
    synchronized (pageContext.getSession()) {
      RDE = (CP_Classes.RatersDataEntry) pageContext.getSession().getAttribute("RDE");
      if (RDE == null) {
        RDE = new CP_Classes.RatersDataEntry();
        pageContext.getSession().setAttribute("RDE", RDE);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.Login logchk;
    synchronized (pageContext.getSession()) {
      logchk = (CP_Classes.Login) pageContext.getSession().getAttribute("logchk");
      if (logchk == null) {
        logchk = new CP_Classes.Login();
        pageContext.getSession().setAttribute("logchk", logchk);
      }
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    CP_Classes.Translate trans;
    synchronized (pageContext.getSession()) {
      trans = (CP_Classes.Translate) pageContext.getSession().getAttribute("trans");
      if (trans == null) {
        trans = new CP_Classes.Translate();
        pageContext.getSession().setAttribute("trans", trans);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.PrelimQuestionController PrelimQController;
    synchronized (pageContext.getSession()) {
      PrelimQController = (CP_Classes.PrelimQuestionController) pageContext.getSession().getAttribute("PrelimQController");
      if (PrelimQController == null) {
        PrelimQController = new CP_Classes.PrelimQuestionController();
        pageContext.getSession().setAttribute("PrelimQController", PrelimQController);
      }
    }
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((logchk.getUserType()));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    
	//response.setHeader("Pragma", "no-cache");
	//response.setHeader("Cache-Control", "no-cache");
	//response.setDateHeader("expires", 0);

String username=(String)session.getAttribute("username");

  if (!logchk.isUsable(username)) 
  {
    out.write(_jsp_string6, 0, _jsp_string6.length);
      } 
  else 
  { 	
	int raterID = RDE.getRaterID();
	int surveyID = RDE.getSurveyID();

	String jobFunction="", ageRange="", gender="", ethnicGroup="", location="", department="";
	String jobLevel=""; 
	int age=0,ethnic=0,gdr=0,jobftn=0,joblvl=0,loc=0, pkDemographic = 0;
	
		int orgID = logchk.getOrg();	
		int compID = logchk.getCompany();
	
		if(raterID == 0)
			raterID = logchk.getPKUser();
			
		/*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 

		User user = new User();
		voUser voU = user.getUserInfo(raterID);
		int fkRater = voU.getPKUser();
		
		//ResultSet ID = Database.getRecord("Select * from [User] where PKUser = '" + raterID + "'");
		//ID.next();
		//int fkRater = ID.getInt(1);
			//int deptID = ID.getInt(2);
		
		voUserDemographic rater = RDE.getRaterInfo(raterID);
		
		pkDemographic = rater.getPKUserDemographic();
		age           = rater.getFKAge();
		ethnic        = rater.getFKEthnic();
		gdr           = rater.getFKGender();
		jobftn        = rater.getFKJobFunction();
		joblvl        = rater.getFKJobLevel();		//pk
		loc           = rater.getFKLocation();

		ageRange    = DemographicEntry.AgeRange(age);
		ethnicGroup = DemographicEntry.Ethnic(ethnic);
		gender      = DemographicEntry.Gender(gdr);
		jobFunction = DemographicEntry.JobFunction(jobftn);
		jobLevel    = DemographicEntry.JobLevel(joblvl);
		location    = DemographicEntry.Location(loc);
		//department  = DemographicEntry.Department(deptID);			
			
		Vector JobFunction = DemographicEntry.getAllJobFunction(orgID);
		Vector JobLevel    = DemographicEntry.getAllJobLevel(orgID);
		Vector AgeRange    = DemographicEntry.getAllAgeRange(orgID);
		Vector Gender      = DemographicEntry.getAllGender(orgID);
		Vector EthnicGroup = DemographicEntry.getAllEthnic(orgID);
		Vector Location    = DemographicEntry.getAllLocation(orgID);
		//ResultSet Department  = DemographicEntry.getAllDepartment(orgID);

		if(request.getParameter("edit") != null) {			
			String jobFunct [] = request.getParameterValues("jobFunction");
			if(jobFunct != null)
				for(int i=0; i<jobFunct.length;i++)
					if(Integer.parseInt(jobFunct[i]) != jobftn)
						jobftn = Integer.parseInt(jobFunct[i]);
			
			String jobLvl [] = request.getParameterValues("jobLevel");
			if(jobLvl != null)
				for(int i=0; i<jobLvl.length;i++)
					if(Integer.parseInt(jobLvl[i]) != joblvl)
						joblvl = Integer.parseInt(jobLvl[i]);
			
			String ageR [] = request.getParameterValues("ageRange");
			if(ageR != null)
			for(int i=0; i<ageR.length;i++)
				if(Integer.parseInt(ageR[i]) != age)
					age = Integer.parseInt(ageR[i]);
					
			String gndr [] = request.getParameterValues("gender");
			if(gndr != null)
			for(int i=0; i<gndr.length;i++)
				if(Integer.parseInt(gndr[i]) != gdr)
					gdr = Integer.parseInt(gndr[i]);
					
			String ethnc [] = request.getParameterValues("ethnicGroup");
			if(ethnc != null)
			for(int i=0; i<ethnc.length;i++)
				if(Integer.parseInt(ethnc[i]) != ethnic)
					ethnic = Integer.parseInt(ethnc[i]);
					
			String lctn [] = request.getParameterValues("location");
			if(lctn != null)
			for(int i=0; i<lctn.length;i++)
				if(Integer.parseInt(lctn[i]) != loc)
					loc = Integer.parseInt(lctn[i]);
			
			Vector<PrelimQuestion> v = PrelimQController.getQuestions(surveyID);
			try {
				DemographicEntry.deleteRecord(pkDemographic);				
				boolean add = DemographicEntry.InsertRecord(raterID, age, ethnic, gdr, jobftn, joblvl, loc);
				if(v.size() > 0){

    out.write(_jsp_string7, 0, _jsp_string7.length);
    				}else{

    out.write(_jsp_string8, 0, _jsp_string8.length);
    				}
			}catch(SQLException SE) {
				if(v.size() > 0){

    out.write(_jsp_string7, 0, _jsp_string7.length);
    				}else{

    out.write(_jsp_string8, 0, _jsp_string8.length);
    				}
			}
			
		}

    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print(( trans.tslt("Job Function") ));
    out.write(_jsp_string10, 0, _jsp_string10.length);
     int t = 0; 
		int exist = 0;
	
    out.write(_jsp_string11, 0, _jsp_string11.length);
    	exist = DemographicEntry.JobFunctionSelected(surveyID);
		if(exist == 0) {
	
    out.write(_jsp_string12, 0, _jsp_string12.length);
     } else { 
    out.write(_jsp_string13, 0, _jsp_string13.length);
     
	    /*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 
	  	for(int i=0; i<JobFunction.size(); i++){
			voJobFunction vo = (voJobFunction) JobFunction.get(i);
			
	  		int funcID = vo.getPKJobFunction();
			String name = vo.getJobFunctionName();

			if(jobFunction.equals(name)) {
	  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((name));
    out.write(_jsp_string16, 0, _jsp_string16.length);
     	  	
	  	} else {  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write('>');
    out.print((name));
    out.write(_jsp_string17, 0, _jsp_string17.length);
     }
		   } 
		   }
	  
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print(( trans.tslt("Job Level") ));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    	
		exist = DemographicEntry.JobLevelSelected(surveyID);
		if(exist == 0) {
	
    out.write(_jsp_string20, 0, _jsp_string20.length);
     } else { 
    out.write(_jsp_string21, 0, _jsp_string21.length);
     
		/*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 
	  	for(int i=0; i<JobLevel.size(); i++){
			voJobLevel vo = (voJobLevel) JobLevel.get(i);
			
	  		int funcID = vo.getPKJobLevel();
			String name = vo.getJobLevelName();
			
			if(joblvl == funcID) {
	  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((name));
    out.write(_jsp_string16, 0, _jsp_string16.length);
     
			} else {  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write('>');
    out.print((name));
    out.write(_jsp_string17, 0, _jsp_string17.length);
     }
		   } 
		   }
	  
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print(( trans.tslt("Age Range") ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    	exist = DemographicEntry.AgeSelected(surveyID);
		if(exist == 0) {
	
    out.write(_jsp_string24, 0, _jsp_string24.length);
     } else { 
    out.write(_jsp_string25, 0, _jsp_string25.length);
     
	  	int temp = 0;
		int funcID1 = 0, funcID2 = 0;
		String name1 = "", name2 = "", name3 = "", name = "";
		
		/*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 
		
		// Temp var j used to loop AgeRange, since AgeRange.next() was called previously, to fix that
		// if j  == 1, then the first object vector will not be retrieved, so similiar to .next()
		int j = 0;
		if(orgID == 1)
			j = 1;
		// AgeRange.next();
		for(;j<AgeRange.size();j++){
			voAge vo = (voAge) AgeRange.get(j);
			
	  		funcID1 = vo.getPKAge();
			name1 = Integer.toString(vo.getAgeRangeTop());
			
			if(temp == 0) {
				name = "Below " + name1;				
				temp++;
			}
			else {
				name3 = Integer.toString(Integer.parseInt(name1)-1);
				name =  name2 + " - " + name3;
			}	
			name2 = name1;

			if(age == funcID1) {
	  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID1));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((name));
    out.write(_jsp_string16, 0, _jsp_string16.length);
     
			} else {  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID1));
    out.write('>');
    out.print((name));
    out.write(_jsp_string17, 0, _jsp_string17.length);
     }
		   }//while

    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((funcID1));
    out.write('>');
    out.print(("Above " + name3));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    			    
		   }
	  
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print(( trans.tslt("Gender") ));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    	exist = DemographicEntry.GenderSelected(surveyID);
		if(exist == 0) {
	
    out.write(_jsp_string29, 0, _jsp_string29.length);
     } else { 
    out.write(_jsp_string30, 0, _jsp_string30.length);
     
		/*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 
	  	for(int i=0; i<Gender.size(); i++){
			voGender vo = (voGender)Gender.get(i);
			
	  		int funcID = vo.getPKGender();
			String name = vo.getGenderDesc();
		
			if(gender.equals(name)) {
	  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((name));
    out.write(_jsp_string16, 0, _jsp_string16.length);
     
			} else {  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write('>');
    out.print((name));
    out.write(_jsp_string17, 0, _jsp_string17.length);
     }
		   }
		   } 
	  
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print(( trans.tslt("Ethnic Group") ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    	exist = DemographicEntry.EthnicSelected(surveyID);
		if(exist == 0) {
	
    out.write(_jsp_string31, 0, _jsp_string31.length);
     } else { 
    out.write(_jsp_string32, 0, _jsp_string32.length);
     
		/*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 
		for(int i=0; i<EthnicGroup.size(); i++){
			voEthnic vo = (voEthnic)EthnicGroup.get(i);
			
	  		int funcID = vo.getPKEthnic();
			String name = vo.getEthnicDesc();
		
			if(ethnicGroup.equals(name)) {
	  
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((funcID));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((name));
    out.write(_jsp_string16, 0, _jsp_string16.length);
     
			} else {  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write('>');
    out.print((name));
    out.write(_jsp_string17, 0, _jsp_string17.length);
     }
		   } 
		   }
	  
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print(( trans.tslt("Location") ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    	exist = DemographicEntry.LocationSelected(surveyID);
		if(exist == 0) {
	
    out.write(_jsp_string34, 0, _jsp_string34.length);
     } else { 
    out.write(_jsp_string35, 0, _jsp_string35.length);
     
		/*************************************************
		*The following was edited by clement at 9-jan-2007
		*************************************************/ 
		
		for(int i=0; i<Location.size(); i++){
			voLocation vo = (voLocation) Location.get(i);
			
	  		int funcID = vo.getPKLocation();
			String name = vo.getLocationName();
		
			if(location.equals(name)) {
	  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((name));
    out.write(_jsp_string16, 0, _jsp_string16.length);
     
			} else {  
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((funcID));
    out.write('>');
    out.print((name));
    out.write(_jsp_string17, 0, _jsp_string17.length);
     }
		   }
		   } 
	  
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print(( trans.tslt("Ok") ));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print(( trans.tslt("Cancel") ));
    out.write(_jsp_string38, 0, _jsp_string38.length);
     } 
    out.write(_jsp_string39, 0, _jsp_string39.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7791540776389363938L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("DemographicEntry.jsp"), 7903383050272394312L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string20;
  private final static char []_jsp_string11;
  private final static char []_jsp_string39;
  private final static char []_jsp_string9;
  private final static char []_jsp_string28;
  private final static char []_jsp_string21;
  private final static char []_jsp_string29;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string30;
  private final static char []_jsp_string35;
  private final static char []_jsp_string33;
  private final static char []_jsp_string25;
  private final static char []_jsp_string26;
  private final static char []_jsp_string14;
  private final static char []_jsp_string37;
  private final static char []_jsp_string22;
  private final static char []_jsp_string38;
  private final static char []_jsp_string36;
  private final static char []_jsp_string17;
  private final static char []_jsp_string15;
  private final static char []_jsp_string34;
  private final static char []_jsp_string13;
  private final static char []_jsp_string24;
  private final static char []_jsp_string16;
  private final static char []_jsp_string5;
  private final static char []_jsp_string32;
  private final static char []_jsp_string31;
  private final static char []_jsp_string12;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string23;
  private final static char []_jsp_string27;
  private final static char []_jsp_string6;
  private final static char []_jsp_string18;
  private final static char []_jsp_string10;
  private final static char []_jsp_string19;
  private final static char []_jsp_string0;
  static {
    _jsp_string20 = "\r\n		\r\n		<select name=\"jobLevel\" disabled>\r\n	".toCharArray();
    _jsp_string11 = "\r\n	<td width=\"252\">\r\n	".toCharArray();
    _jsp_string39 = "\r\n</form>\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string9 = "\r\n\r\n<form name=\"DemographicEntry\" method=\"post\">\r\n<table width=\"391\" border=\"0\" font style='font-size:10.0pt;font-family:Arial'>\r\n  <tr>\r\n    <td width=\"115\" align=\"right\">".toCharArray();
    _jsp_string28 = " : </td>\r\n    <td>&nbsp;</td>\r\n    <td>\r\n	\r\n	".toCharArray();
    _jsp_string21 = "	\r\n      <select name=\"jobLevel\">\r\n	  ".toCharArray();
    _jsp_string29 = "\r\n		<select name=\"gender\" disabled>\r\n	".toCharArray();
    _jsp_string8 = "					<script>\r\n						window.location.href = \"Questionnaire.jsp\";\r\n					</script>\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n \r\n<html>\r\n<head>\r\n<title>Demographic Entry</title>\r\n\r\n<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n\r\n<style type=\"text/css\">\r\n<!--\r\nbody {\r\n	background-color: white; //#eaebf4;\r\n}\r\n-->\r\n</style></head>\r\n\r\n<body>\r\n".toCharArray();
    _jsp_string4 = "\r\n\r\n\r\n\r\n<script language=\"javascript\">\r\n//Edited by Xuehai 02 Jun 2011. Remove 'void'. Enable to run on different browers like Chrome&Firefox.\r\n//void function openQuestionnaire(form)\r\nfunction openQuestionnaire(form)\r\n{	\r\n	form.action= \"DemographicEntry.jsp?edit=1\";\r\n	form.method = \"post\";\r\n	form.submit();\r\n}\r\n\r\n//Edited by Xuehai 02 Jun 2011. Remove 'void'. Enable to run on different browers like Chrome&Firefox.\r\n//void function cancel(form)\r\nfunction cancel(form)\r\n{	\r\n	var usertype = ".toCharArray();
    _jsp_string30 = "	\r\n      <select name=\"gender\">\r\n	  ".toCharArray();
    _jsp_string35 = "	\r\n      <select name=\"location\">\r\n	  ".toCharArray();
    _jsp_string33 = "\r\n	  	  	<option value = ".toCharArray();
    _jsp_string25 = "	\r\n      <select name=\"ageRange\">\r\n	  ".toCharArray();
    _jsp_string26 = "		   \r\n		<option value = ".toCharArray();
    _jsp_string14 = "\r\n	  	<option value = ".toCharArray();
    _jsp_string37 = "  \" onclick=\"openQuestionnaire(this.form)\"></td>\r\n<td width=\"21\">&nbsp;</td>\r\n<td width=\"225\"><input type=\"button\" name=\"btnCancel\" value=\"".toCharArray();
    _jsp_string22 = "\r\n    </select></td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td>&nbsp;</td>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td align=\"right\">".toCharArray();
    _jsp_string38 = "\" onclick=\"cancel(this.form)\"></td>\r\n</tr>\r\n</table>\r\n".toCharArray();
    _jsp_string36 = "\r\n    </select></td>\r\n  </tr>\r\n  </table>\r\n<p></p>\r\n<table>\r\n<tr>\r\n<td width=\"135\" align=\"right\"><input type=\"button\" name=\"btnOk\" value=\"  ".toCharArray();
    _jsp_string17 = "	  \r\n	  ".toCharArray();
    _jsp_string15 = " selected>".toCharArray();
    _jsp_string34 = "\r\n		<select name=\"location\" disabled>\r\n	".toCharArray();
    _jsp_string13 = "	\r\n      <select name=\"jobFunction\">\r\n	  ".toCharArray();
    _jsp_string24 = "\r\n		<select name=\"ageRange\" disabled>\r\n	".toCharArray();
    _jsp_string16 = "\r\n	  ".toCharArray();
    _jsp_string5 = "\r\n	if(usertype == 4) {\r\n		window.location.href = \"RatersToDoList.jsp\";\r\n		//window.close();\r\n//		opener.location = \"RatersToDoList.jsp\"\r\n	}else {\r\n		window.location.href = \"Questionnaire.jsp\";\r\n		//window.close();\r\n		//opener.location = \"Questionnaire.jsp\"\r\n	}\r\n}\r\n</script>\r\n\r\n".toCharArray();
    _jsp_string32 = "	\r\n      <select name=\"ethnicGroup\">\r\n	  ".toCharArray();
    _jsp_string31 = "\r\n		<select name=\"ethnicGroup\" disabled>\r\n	".toCharArray();
    _jsp_string12 = "\r\n		<select name=\"jobFunction\" disabled>\r\n	".toCharArray();
    _jsp_string7 = "					<script>\r\n						window.location.href = \"PrelimQAnswers.jsp\";\r\n					</script>\r\n".toCharArray();
    _jsp_string3 = "  \r\n".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string23 = " : </td>\r\n    <td>&nbsp;</td>\r\n    <td>\r\n	".toCharArray();
    _jsp_string27 = "   \r\n".toCharArray();
    _jsp_string6 = " <font size=\"2\">\r\n   \r\n    	    	<script>\r\n	parent.location.href = \"index.jsp\";\r\n</script>\r\n".toCharArray();
    _jsp_string18 = "\r\n      </select></td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td>&nbsp;</td>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td align=\"right\">".toCharArray();
    _jsp_string10 = " : </td>\r\n    <td width=\"10\">&nbsp;</td>\r\n    ".toCharArray();
    _jsp_string19 = " :</td>\r\n    <td>&nbsp;</td>\r\n    <td>\r\n	\r\n	".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
