/*
 * JSP generated by Resin Professional 4.0.36 (built Fri, 26 Apr 2013 03:33:09 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.text.DateFormat;
import java.util.*;
import java.util.Date;
import java.text.*;
import java.lang.String;
import CP_Classes.vo.votblSurvey;
import CP_Classes.vo.votblOrganization;

public class _importlanguage__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");
    response.setCharacterEncoding("utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.Login logchk;
    synchronized (pageContext.getSession()) {
      logchk = (CP_Classes.Login) pageContext.getSession().getAttribute("logchk");
      if (logchk == null) {
        logchk = new CP_Classes.Login();
        pageContext.getSession().setAttribute("logchk", logchk);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.DevelopmentGuide Rpt9;
    synchronized (pageContext.getSession()) {
      Rpt9 = (CP_Classes.DevelopmentGuide) pageContext.getSession().getAttribute("Rpt9");
      if (Rpt9 == null) {
        Rpt9 = new CP_Classes.DevelopmentGuide();
        pageContext.getSession().setAttribute("Rpt9", Rpt9);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.Setting setting;
    synchronized (pageContext.getSession()) {
      setting = (CP_Classes.Setting) pageContext.getSession().getAttribute("setting");
      if (setting == null) {
        setting = new CP_Classes.Setting();
        pageContext.getSession().setAttribute("setting", setting);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.Create_Edit_Survey CE_Survey;
    synchronized (pageContext.getSession()) {
      CE_Survey = (CP_Classes.Create_Edit_Survey) pageContext.getSession().getAttribute("CE_Survey");
      if (CE_Survey == null) {
        CE_Survey = new CP_Classes.Create_Edit_Survey();
        pageContext.getSession().setAttribute("CE_Survey", CE_Survey);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.User user;
    synchronized (pageContext.getSession()) {
      user = (CP_Classes.User) pageContext.getSession().getAttribute("user");
      if (user == null) {
        user = new CP_Classes.User();
        pageContext.getSession().setAttribute("user", user);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.Translate trans;
    synchronized (pageContext.getSession()) {
      trans = (CP_Classes.Translate) pageContext.getSession().getAttribute("trans");
      if (trans == null) {
        trans = new CP_Classes.Translate();
        pageContext.getSession().setAttribute("trans", trans);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.User_Jenty userJ;
    synchronized (pageContext.getSession()) {
      userJ = (CP_Classes.User_Jenty) pageContext.getSession().getAttribute("userJ");
      if (userJ == null) {
        userJ = new CP_Classes.User_Jenty();
        pageContext.getSession().setAttribute("userJ", userJ);
      }
    }
    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.ImportLanguage ImportLanguage;
    synchronized (pageContext.getSession()) {
      ImportLanguage = (CP_Classes.ImportLanguage) pageContext.getSession().getAttribute("ImportLanguage");
      if (ImportLanguage == null) {
        ImportLanguage = new CP_Classes.ImportLanguage();
        pageContext.getSession().setAttribute("ImportLanguage", ImportLanguage);
      }
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((trans.tslt("Please complete the necessary fields")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    

String username=(String)session.getAttribute("username");

  if (!logchk.isUsable(username)) 
  {
    out.write(_jsp_string4, 0, _jsp_string4.length);
      } 
  else 
  { 

	if(request.getParameter("preview") != null)
	{
		//Import Type Code for URL String
		//    For 1 to 11 refer to ImportExport.jsp
		//	  12) Import Language
		
		int iLanguage = (request.getParameter("lang") == null)?0:Integer.parseInt(request.getParameter("lang"));

    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((iLanguage));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    
	}
	
	if(request.getParameter("view") != null)
	{
		String file_name="UploadLanguageTemplate.xls";
        String output = setting.getReport_Path_Template() + "\\" + file_name;
		File f = new File (output);
		response.reset();
		
		//set the content type(can be excel/word/powerpoint etc..)
		response.setContentType ("application/xls");
		//set the header and also the Name by which user will be prompted to save
		response.addHeader ("Content-Disposition", "attachment;filename=\"UploadLanguageTemplate.xls\"");
		
		//get the file name
		String name = f.getName().substring(f.getName().lastIndexOf("/") + 1,f.getName().length());
		//OPen an input stream to the file and post the file contents thru the 
		//servlet output stream to the client m/c
	
		InputStream in = new FileInputStream(f);
		ServletOutputStream outs = response.getOutputStream();
		
		int bit = 256;
		int i = 0;

		try {
			while ((bit) >= 0) {
				bit = in.read();
				outs.write(bit);
			}

		} catch (IOException ioe) {
			ioe.printStackTrace(System.out);
		}
		outs.flush();
		outs.close();
		in.close();	
	}

    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((trans.tslt("Import Language")));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((trans.tslt("Click 'View Template' to download the template")));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((trans.tslt("Complete the Excel document")));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((trans.tslt("Select the type of Language")));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((trans.tslt("Click 'Process' to upload the Excel document")));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((trans.tslt("Language")));
    out.write(_jsp_string12, 0, _jsp_string12.length);
     	//Used array of string for language dropbox, Chun Yeong 13 Jul 2011
		
		int lang = 0;
		if(request.getParameter("lang") != null){
			lang = Integer.parseInt(request.getParameter("lang"));
		}
		//Modified by Yiping
		//10/01/2012
		//The sequence of the languages is not the same as in table TB_Translation
		String[] languages = {"English", "Indonesian", "Thai", "Chinese(Simplified)", "Chinese(Traditional)", "Korean"};
		for(int i=1; i<languages.length; i++) {
			if(lang == i) {
		
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((i));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((languages[i]));
    out.write(_jsp_string15, 0, _jsp_string15.length);
      } else { 
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((i));
    out.write('>');
    out.print((languages[i]));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    	}
		}
		
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
		if(request.getParameter("path") != null) 
		{
			
			String reportPath = setting.getUploadPath() + "\\" + request.getParameter("path");
			
			if(request.getParameter("type") != null)
			{
				int iType = Integer.parseInt(request.getParameter("type"));
				
				int language = Integer.parseInt(request.getParameter("lang"));
				
				//Initial String[]
				String[] sImportStatus = {"",""};
				
				//Import Type Check
				if(iType == 12)
					sImportStatus = ImportLanguage.importFromFile(iType, language, reportPath);

    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print(((sImportStatus[0].equals(""))?"":("<br>" + sImportStatus[0])));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    
   			} //end if(request.getParameter("type") != null)
   		} //end if(request.getParameter("path") != null)
   		
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((trans.tslt("View Template")));
    out.write(_jsp_string21, 0, _jsp_string21.length);
     if(logchk.getCompany() != 2 || logchk.getUserType() == 1) {

    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((trans.tslt("Process")));
    out.write(_jsp_string23, 0, _jsp_string23.length);
       
   			} else { 

    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((trans.tslt("Process")));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    
   			}

    out.write(_jsp_string25, 0, _jsp_string25.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string26, 0, _jsp_string26.length);
    
	Calendar c = Calendar.getInstance();
	int year = c.get(Calendar.YEAR);

    out.write(_jsp_string27, 0, _jsp_string27.length);
     // Denise 05/01/2010 update new email address 
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((year));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    	}	
    out.write(_jsp_string30, 0, _jsp_string30.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7791540776389363938L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("ImportLanguage.jsp"), 185236064462285799L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("Footer.jsp"), -9159279428429745474L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string19;
  private final static char []_jsp_string15;
  private final static char []_jsp_string11;
  private final static char []_jsp_string20;
  private final static char []_jsp_string17;
  private final static char []_jsp_string9;
  private final static char []_jsp_string21;
  private final static char []_jsp_string3;
  private final static char []_jsp_string23;
  private final static char []_jsp_string14;
  private final static char []_jsp_string30;
  private final static char []_jsp_string28;
  private final static char []_jsp_string5;
  private final static char []_jsp_string22;
  private final static char []_jsp_string29;
  private final static char []_jsp_string7;
  private final static char []_jsp_string4;
  private final static char []_jsp_string25;
  private final static char []_jsp_string18;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string27;
  private final static char []_jsp_string0;
  private final static char []_jsp_string13;
  private final static char []_jsp_string24;
  private final static char []_jsp_string12;
  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string26;
  private final static char []_jsp_string2;
  static {
    _jsp_string19 = "</font></b> </font>\r\n".toCharArray();
    _jsp_string15 = "</option>\r\n		".toCharArray();
    _jsp_string11 = ".</font></li>\r\n      </ul>\r\n      </td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"6\"><b> <font face=\"Arial\" size=\"2\">".toCharArray();
    _jsp_string20 = "\r\n      </td>\r\n    </tr>\r\n    <tr>\r\n      <td  align=\"center\"  style=\"border-top-style: none; border-top-width: medium\">&nbsp;</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"27\" align=\"center\"><font face=\"Arial\">&nbsp; </font> </td>\r\n      <td width=\"172\" align=\"center\"><font face=\"Arial\">\r\n      		<input type=\"button\" name=\"VTemplate\" value=\"".toCharArray();
    _jsp_string17 = "\r\n			\r\n		</select>\r\n        </font></font></td>\r\n      \r\n    </tr>\r\n    <tr>\r\n      <td width=\"503\" colspan=\"4\"><font face=\"Arial\"> \r\n        ".toCharArray();
    _jsp_string9 = ".</font></li>\r\n      	   	<li><font face=\"Arial\" size=\"2\">".toCharArray();
    _jsp_string21 = "\" onClick=\"view(this.form,1)\"></font> </td>\r\n      <td width=\"304\" align=\"center\" rowspan=\"2\" colspan=\"2\"><font size=\"2\"> <font face=\"Arial\">\r\n        ".toCharArray();
    _jsp_string3 = "\");\r\n	}\r\n}\r\n\r\nfunction view(form)\r\n{\r\n	var query = \"ImportLanguage.jsp?view=1\";\r\n	form.action = query;\r\n	form.method = \"post\";\r\n	form.submit();\r\n}  \r\n</script>\r\n<body>\r\n<font face=\"Arial\">\r\n".toCharArray();
    _jsp_string23 = "\" name=\"btnPreview\" style=\"float: right\"  onclick=\"chkSelect(this.form, this.form.lang)\">\r\n".toCharArray();
    _jsp_string14 = " selected>".toCharArray();
    _jsp_string30 = "\r\n</font>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string28 = "\r\n		<td align=\"center\" height=\"5\" valign=\"top\"><font size=\"1\" color=\"navy\" face=\"Arial\">&nbsp;&nbsp;<a style=\"TEXT-DECORATION: none; color:navy;\" href=\"Login.jsp\">Home</a>&nbsp;| <a color=\"navy\" face=\"Arial\">&nbsp;<a style=\"TEXT-DECORATION: none; color:navy;\" href=\"mailto:3SixtyAdmin@pcc.com.sg?subject=Regarding:\">Contact \r\n		Us</a><a color=\"navy\" face=\"Arial\" href=\"termofuse.jsp\" target=\"_blank\"><span style=\"color: #000080; text-decoration: none\"> | Terms of Use </span></a>| <span style=\"color: #000080; text-decoration: none\"><a style=\"TEXT-DECORATION: none; color:navy;\" href=\"http://www.pcc.com.sg/\" target=\"_blank\">PCC Website</a></span></font></td></tr><tr>\r\n		<font size=\"2\" face=\"Arial\" style=\"font-size: 14pt\" color=\"#000080\">\r\n   \r\n		<td align=\"center\" height=\"5\" valign=\"top\">\r\n		<font size=\"1\" color=\"navy\" face=\"Arial\">&nbsp;Copyright &copy; ".toCharArray();
    _jsp_string5 = "\r\n			<script>\r\n				var myWindow=window.open('ImportUpload.jsp?type=12&lang=".toCharArray();
    _jsp_string22 = "\r\n        		<input type=\"button\" value=\"".toCharArray();
    _jsp_string29 = " Pacific Century Consulting Pte Ltd. All Rights Reserved.\r\n		</font>\r\n		</td>\r\n		\r\n	</tr>\r\n		\r\n</table>\r\n\r\n    </tr>\r\n  </table>\r\n</form>\r\n<font face=\"Arial\">\r\n".toCharArray();
    _jsp_string7 = "\r\n</font>\r\n\r\n<form name=\"ImportLanguage\" action=\"ImportLanguage.jsp\" method=\"post\">\r\n  <table border=\"0\" width=\"505\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-width:0px; \" bordercolor=\"#3399FF\">\r\n    <tr>\r\n      <td width=\"505\" colspan=\"6\"><b> <font face=\"Arial\" size=\"2\" color=\"#000080\"> ".toCharArray();
    _jsp_string4 = "\r\n	<script>\r\n		parent.location.href = \"index.jsp\";\r\n	</script>\r\n".toCharArray();
    _jsp_string25 = "\r\n        </font></td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"458\" align=\"center\" colspan=\"5\">&nbsp;</td>\r\n    </tr>\r\n    <tr>\r\n    	\r\n\r\n".toCharArray();
    _jsp_string18 = "\r\n        <b><font color=\"#0000FF\">".toCharArray();
    _jsp_string16 = "\r\n				<option value = ".toCharArray();
    _jsp_string6 = "','windowRef','scrollbars=no,width=400,height=200');\r\n				myWindow.document.title=\"Import Language Translation\";	\r\n				myWindow.moveTo(x,y);\r\n			</script>\r\n".toCharArray();
    _jsp_string27 = "\r\n\r\n<table border=\"0\" width=\"610\" height=\"26\" id=\"table1\">\r\n\r\n	<tr>\r\n		<font size=\"2\" face=\"Arial\" style=\"font-size: 14pt\" color=\"#000080\"/>\r\n		".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string13 = "\r\n	        	<option value = ".toCharArray();
    _jsp_string24 = "\" name=\"btnPreview\" style=\"float: right\" disabled>\r\n".toCharArray();
    _jsp_string12 = " : </font></b><font face=\"Arial\" size=\"2\"> <font face=\"Arial\">\r\n      \r\n        <select size=\"1\" name=\"lang\">\r\n		".toCharArray();
    _jsp_string10 = ".</font></li>\r\n           	<li><font face=\"Arial\" size=\"2\">".toCharArray();
    _jsp_string8 = "</font></b></td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"505\" colspan=\"6\">\r\n      <ul>\r\n      		<li><font face=\"Arial\" size=\"2\">".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n\r\n".toCharArray();
    _jsp_string26 = "\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n</head>\r\n<SCRIPT LANGUAGE=\"JavaScript\">\r\nvar target\r\nvar x = parseInt(window.screen.width) / 2 - 500;  // the number 250 is the exact half of the width of the pop-up and so should be changed according to the size of the pop-up\r\nvar y = parseInt(window.screen.height) / 2 - 300;  // the number 125 is the exact half of the height of the pop-up and so should be changed according to the size of the pop-up\r\n		\r\nfunction check(field)\r\n{\r\n	var check= false;\r\n	\r\n	for (i = 0; i < field.length; i++) \r\n	{\r\n		if(field[i].checked)\r\n		{\r\n			target = field[i].value;\r\n			check = true;\r\n		}\r\n		else if(field[i].selected != \"\" && check == false)\r\n		{\r\n			if(field[i].value != \"\")\r\n			{\r\n				check = true;\r\n			}\r\n		}\r\n	}\r\n\r\n	return check;\r\n}\r\n\r\nfunction chkSelect(form,field)\r\n{	\r\n	x = document.ImportLanguage\r\n	var flag = true;\r\n	if(flag)\r\n	{\r\n		form.action=\"ImportLanguage.jsp?preview=1\";\r\n		form.method=\"post\";\r\n		form.submit();\r\n	}\r\n	else\r\n	{\r\n		alert(\"".toCharArray();
  }
}
