/*
 * JSP generated by Resin Professional 4.0.36 (built Fri, 26 Apr 2013 03:33:09 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.text.DateFormat;
import java.util.*;
import java.util.Date;
import java.text.*;
import java.lang.String;
import CP_Classes.vo.votblSurvey;
import CP_Classes.vo.voJob;

public class _nomination_0assigntr__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");
    response.setCharacterEncoding("utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    CP_Classes.Login logchk;
    synchronized (pageContext.getSession()) {
      logchk = (CP_Classes.Login) pageContext.getSession().getAttribute("logchk");
      if (logchk == null) {
        logchk = new CP_Classes.Login();
        pageContext.getSession().setAttribute("logchk", logchk);
      }
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    CP_Classes.Database db;
    synchronized (pageContext.getSession()) {
      db = (CP_Classes.Database) pageContext.getSession().getAttribute("db");
      if (db == null) {
        db = new CP_Classes.Database();
        pageContext.getSession().setAttribute("db", db);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.Create_Edit_Survey CE_Survey;
    synchronized (pageContext.getSession()) {
      CE_Survey = (CP_Classes.Create_Edit_Survey) pageContext.getSession().getAttribute("CE_Survey");
      if (CE_Survey == null) {
        CE_Survey = new CP_Classes.Create_Edit_Survey();
        pageContext.getSession().setAttribute("CE_Survey", CE_Survey);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.AssignTarget_Rater assignTR;
    synchronized (pageContext.getSession()) {
      assignTR = (CP_Classes.AssignTarget_Rater) pageContext.getSession().getAttribute("assignTR");
      if (assignTR == null) {
        assignTR = new CP_Classes.AssignTarget_Rater();
        pageContext.getSession().setAttribute("assignTR", assignTR);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.Report_DeleteSurvey RptX;
    synchronized (pageContext.getSession()) {
      RptX = (CP_Classes.Report_DeleteSurvey) pageContext.getSession().getAttribute("RptX");
      if (RptX == null) {
        RptX = new CP_Classes.Report_DeleteSurvey();
        pageContext.getSession().setAttribute("RptX", RptX);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.Translate trans;
    synchronized (pageContext.getSession()) {
      trans = (CP_Classes.Translate) pageContext.getSession().getAttribute("trans");
      if (trans == null) {
        trans = new CP_Classes.Translate();
        pageContext.getSession().setAttribute("trans", trans);
      }
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((trans.tslt("Please select Survey")));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((trans.tslt("Please select Survey")));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((trans.tslt("Please select a survey")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((trans.tslt("Please select Survey")));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((trans.tslt("Delete Survey")));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((trans.tslt("Please select Survey")));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    


String username=(String)session.getAttribute("username");

  if (!logchk.isUsable(username)) 
  {
    out.write(_jsp_string11, 0, _jsp_string11.length);
      } 
  else 
  { 

assignTR.setGroupID(0);

if(request.getParameter("job") != null)
{
	int var1 = new Integer(request.getParameter("selJob")).intValue();
	CE_Survey.setJobPos_ID(var1);
}

if(request.getParameter("survey") != null)
{
	int var1 = new Integer(request.getParameter("Survey")).intValue();
	CE_Survey.setSurvey_ID(var1); 

    out.write(_jsp_string12, 0, _jsp_string12.length);
    pageContext.forward("SurveyDetail.jsp");if (true) return;
    out.write(_jsp_string13, 0, _jsp_string13.length);
    
}

if(request.getParameter("process") != null)
{
	int var1 = new Integer(request.getParameter("Survey")).intValue();
	CE_Survey.setSurvey_ID(var1); 

    out.write(_jsp_string12, 0, _jsp_string12.length);
    pageContext.forward("SurveyResult.jsp");if (true) return;
    out.write(_jsp_string13, 0, _jsp_string13.length);
    
}

if(request.getParameter("add") != null)
{
	CE_Survey.setJobPos_ID(0);
	CE_Survey.setSurveyStatus(0);
	CE_Survey.setPurpose(0);
	CE_Survey.setSurvey_ID(0);
	CE_Survey.setCompetencyLevel(0);
	assignTR.set_selectedTargetID(0);

    out.write(_jsp_string14, 0, _jsp_string14.length);
    
}	

if(request.getParameter("assign") != null)
{
	int var1 = new Integer(request.getParameter("Survey")).intValue();
	CE_Survey.setSurvey_ID(var1);
	assignTR.setGroupID(0);
	assignTR.setTargetID(0);
	CE_Survey.setJobPos_ID(0);
	CE_Survey.setSurveyStatus(0);
	CE_Survey.setPurpose(0);
	CE_Survey.setCompetencyLevel(0);
	assignTR.set_selectedTargetID(0);
	assignTR.set_selectedAssID(0);

	int SurvSta = 0;
	
	votblSurvey rs_Survey1 = CE_Survey.getSurveyDetail(CE_Survey.getSurvey_ID());
	if(rs_Survey1 != null)
	{
		SurvSta = rs_Survey1.getSurveyStatus();
		CE_Survey.setSurveyStatus(SurvSta);
	}
		

    out.write(_jsp_string12, 0, _jsp_string12.length);
    pageContext.forward("AssignTarget_Rater.jsp");if (true) return;
    out.write(_jsp_string13, 0, _jsp_string13.length);
    
}

if(request.getParameter("copy") != null)
{
	int var1 = new Integer(request.getParameter("Survey")).intValue();
	CE_Survey.setSurvey_ID(var1); 

    out.write(_jsp_string15, 0, _jsp_string15.length);
        
}

if(request.getParameter("del") != null)
{
	int FKOrg = 0;
	int var1 = new Integer(request.getParameter("Survey")).intValue();
	
	votblSurvey rs_Survey = CE_Survey.getSurveyDetail(var1);
	if(rs_Survey != null)
		FKOrg = rs_Survey.getFKOrganization();
	
	String filename = RptX.DeleteReport(var1);
	CE_Survey.addDeletedSurvey(var1, filename, FKOrg, logchk.getCompany(), logchk.getPKUser());

	
}

/************************************************** ADDING TOGGLE FOR SORTING PURPOSE *************************************************/
					
	if(request.getParameter("sorting") != null)
	{	 
		int type = new Integer(request.getParameter("sorting")).intValue();
		int toggle = CE_Survey.getToggle();	//0=asc, 1=desc
		CE_Survey.setSortType(type);
		
		if(toggle == 0)
			toggle = 1;
		else
			toggle = 0;
			
		CE_Survey.setToggle(toggle);
	} 
	else
	{
		CE_Survey.setSortType(1);
	}


    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((trans.tslt("Job Position")));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
	//modified by suwandy on 1 dec 2004 to filter out the job position
	//change by Thant Thura From Resultset To Vector
	Vector veJob = CE_Survey.getJobForOrg(logchk.getOrg());
        Iterator iterJob=veJob.iterator();
	while(iterJob.hasNext())
	{
                voJob vo=(voJob)iterJob.next();
		int JobPosition_ID = vo.getJobPositionID();
		String JobPosition_Desc =vo.getJobPosition();

		if(CE_Survey.getJobPos_ID() == JobPosition_ID)
		{

    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((JobPosition_ID));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((JobPosition_Desc));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    		}
		else
		{

    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((JobPosition_ID));
    out.write('>');
    out.print((JobPosition_Desc));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    		}	
		
	}
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((trans.tslt("Show")));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((trans.tslt("Assign Target/Rater For Specific Survey")));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((trans.tslt("Name")));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((trans.tslt("Opening Date")));
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((trans.tslt("Deadline")));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((trans.tslt("Closed Date")));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((trans.tslt("Status")));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((trans.tslt("Organisation")));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    	
	int Survey_ID=0;
	int JobPosID1=0;
	String Survey_Name=" ";
	String month = " ";
	String DateOpened = " ";
	String DeadlineDate = " ";
	int db_SurveyStatus=0;
	String SurveyStatus=" ";
	int iJobPos_ID=0;
        iJobPos_ID=CE_Survey.getJobPos_ID();
	//modified by Jenty on 1 Dec 04 in order to filter only the survey which the subordinate has been assigned as a target.
	//modified by Thant Thura From Resultset To Vector
	SimpleDateFormat month_view= new SimpleDateFormat ("MM/yyyy");
	SimpleDateFormat day_view= new SimpleDateFormat ("dd/MM/yyyy");
	Vector veSurD = CE_Survey.getRecord_Survey(logchk.getPKUser(),iJobPos_ID);		
	System.out.println(logchk.getPKUser() +"-----"+iJobPos_ID);
    Iterator iterSurD=veSurD.iterator();
	while(iterSurD.hasNext())
	{
        votblSurvey vo=(votblSurvey)iterSurD.next(); 
		int Surv_ID = vo.getSurveyID();
		String Surv_Name = vo.getSurveyName();
		DateOpened = vo.getDateOpened();
		DeadlineDate = vo.getDeadlineSubmission();
		db_SurveyStatus = vo.getSurveyStatus();
		String anal_Date = vo.getAnalysisDate();
		String OrganizationName = vo.getOrganizationName();
				
		if(anal_Date == null)
			anal_Date = " ";
					
		if(db_SurveyStatus == 1)
			SurveyStatus ="Open";
		else if(db_SurveyStatus == 2)
			SurveyStatus ="Closed";										
		else if(db_SurveyStatus == 3)
			SurveyStatus ="Not Commissioned";
		else if(db_SurveyStatus == 0)
			SurveyStatus ="Not Available";

    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((Surv_ID));
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((Surv_Name));
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((DateOpened));
    out.write(_jsp_string34, 0, _jsp_string34.length);
    out.print((DeadlineDate));
    out.write(_jsp_string34, 0, _jsp_string34.length);
    out.print((anal_Date));
    out.write(_jsp_string35, 0, _jsp_string35.length);
    out.print((SurveyStatus));
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((OrganizationName));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    	}	
    out.write(_jsp_string38, 0, _jsp_string38.length);
    out.print((trans.tslt("Assign Target/Rater")));
    out.write(_jsp_string39, 0, _jsp_string39.length);
    }	
    out.write(_jsp_string40, 0, _jsp_string40.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string41, 0, _jsp_string41.length);
    
	Calendar c = Calendar.getInstance();
	int year = c.get(Calendar.YEAR);

    out.write(_jsp_string42, 0, _jsp_string42.length);
     // Denise 05/01/2010 update new email address 
    out.write(_jsp_string43, 0, _jsp_string43.length);
    out.print((year));
    out.write(_jsp_string44, 0, _jsp_string44.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7791540776389363938L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("Nomination_AssignTR.jsp"), 5501214610249507761L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("Footer.jsp"), -9159279428429745474L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string18;
  private final static char []_jsp_string12;
  private final static char []_jsp_string35;
  private final static char []_jsp_string3;
  private final static char []_jsp_string25;
  private final static char []_jsp_string37;
  private final static char []_jsp_string7;
  private final static char []_jsp_string0;
  private final static char []_jsp_string17;
  private final static char []_jsp_string8;
  private final static char []_jsp_string23;
  private final static char []_jsp_string32;
  private final static char []_jsp_string39;
  private final static char []_jsp_string44;
  private final static char []_jsp_string29;
  private final static char []_jsp_string31;
  private final static char []_jsp_string19;
  private final static char []_jsp_string40;
  private final static char []_jsp_string5;
  private final static char []_jsp_string43;
  private final static char []_jsp_string22;
  private final static char []_jsp_string4;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string36;
  private final static char []_jsp_string9;
  private final static char []_jsp_string24;
  private final static char []_jsp_string13;
  private final static char []_jsp_string21;
  private final static char []_jsp_string42;
  private final static char []_jsp_string28;
  private final static char []_jsp_string34;
  private final static char []_jsp_string14;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string33;
  private final static char []_jsp_string27;
  private final static char []_jsp_string20;
  private final static char []_jsp_string10;
  private final static char []_jsp_string11;
  private final static char []_jsp_string38;
  private final static char []_jsp_string15;
  private final static char []_jsp_string26;
  private final static char []_jsp_string30;
  private final static char []_jsp_string41;
  static {
    _jsp_string18 = "			\r\n<option value=".toCharArray();
    _jsp_string12 = "\r\n	".toCharArray();
    _jsp_string35 = "&nbsp</td>\r\n    <td align=\"center\" style=\"border-style: solid; border-width: 1px\" bordercolor=\"#3399FF\"><font size=\"2\">".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n\r\n".toCharArray();
    _jsp_string25 = "</u></a></font></b></th>\r\n<font face=\"Tahoma\">\r\n<th width=\"70\" bgcolor=\"#000080\"><b><font style=\"color: white\" size=\"2\"><a href=\"Nomination_AssignTR.jsp?sorting=2\"><font style='color:white'><u>".toCharArray();
    _jsp_string37 = "</font></td>\r\n\r\n  </tr>\r\n  ".toCharArray();
    _jsp_string7 = "\");\r\n	}\r\n\r\n}\r\n\r\nfunction job(form,field)\r\n{\r\n	form.action=\"Nomination_AssignTR.jsp?job=1\";\r\n	form.method=\"post\";\r\n	form.submit();	\r\n}\r\n\r\nfunction copy(form,field)\r\n{\r\n	if(check(field))\r\n	{\r\n		form.action=\"Nomination_AssignTR.jsp?copy=1\";\r\n		form.method=\"post\";\r\n		form.submit();	\r\n	}\r\n	else\r\n	{\r\n		alert(\"".toCharArray();
    _jsp_string0 = "  \r\n        \r\n                 \r\n".toCharArray();
    _jsp_string17 = ": </font></b></td>\r\n		<td width=\"172\"><font face=\"Arial\" size=\"2\">\r\n				<span style=\"font-size: 11pt\">\r\n				<select size=\"1\" name=\"selJob\" >\r\n\r\n	<option value =\"0\" selected>All</option>\r\n".toCharArray();
    _jsp_string8 = "\");\r\n	}\r\n\r\n}\r\n\r\nfunction DeleteAway(form,field)\r\n{\r\n	if(check(field))\r\n	{\r\n		if(confirm(\"".toCharArray();
    _jsp_string23 = "\" name=\"btnShow\" onclick=\"job(this.form)\" style=\"float: right\"></td>\r\n	</tr>\r\n</table>\r\n\r\n\r\n				</td>\r\n\r\n			</tr>\r\n	<tr>\r\n				<td width=\"14%\">&nbsp;</td>\r\n				<td width=\"22%\">&nbsp;</td>\r\n				<td width=\"150\">&nbsp;</td>\r\n		<td width=\"164\">&nbsp;</td>\r\n\r\n		<td width=\"79\">&nbsp;</td>\r\n\r\n			</tr>\r\n	<tr>\r\n				<td width=\"14%\"> <font face=\"Arial\" size=\"2\">\r\n   \r\n    			<p align=\"left\">\r\n    			<a onclick=\"clickAll(this.form)\">\r\n				&nbsp;</a></td>\r\n				<td width=\"22%\">&nbsp;</td>\r\n				<td width=\"150\">&nbsp;</td>\r\n		<td width=\"164\">&nbsp;</td>\r\n\r\n		<td width=\"79\">&nbsp;</td>\r\n\r\n			</tr>\r\n	</table>\r\n<table width=\"610\" border=\"1\" style='font-size:11.0pt;font-family:Arial' bordercolor=\"#3399FF\">\r\n<th bgcolor=\"#000080\" width=\"823\"><font size=\"2\" color=\"#FFFFFF\">\r\n".toCharArray();
    _jsp_string32 = " name=\"Survey\" ondblclick=\"AssignTarget(this.form,this.form.Survey)\"></font></span></font></td>\r\n				\r\n\r\n				<td width=\"50%\" style=\"border-style:solid; border-width:1px; \" bordercolor=\"#3399FF\"><font size=\"2\">&nbsp".toCharArray();
    _jsp_string39 = "\" name=\"btnAssign\" style=\"float: right\" onclick=\"AssignTarget(this.form,this.form.Survey)\"></td>\r\n	</tr>\r\n</table>\r\n</form>\r\n".toCharArray();
    _jsp_string44 = " Pacific Century Consulting Pte Ltd. All Rights Reserved.\r\n		</font>\r\n		</td>\r\n		\r\n	</tr>\r\n		\r\n</table>\r\n\r\n</font>\r\n</body>\r\n\r\n\r\n</html>".toCharArray();
    _jsp_string29 = "</u></a></font></b></th>\r\n<th width=\"82\" bgcolor=\"#000080\"></font>\r\n<span style=\"font-weight: 400\"><b><font size=\"2\" style=\"color: white\"><a href=\"Nomination_AssignTR.jsp?sorting=6\"><font style='color:white'><u>".toCharArray();
    _jsp_string31 = "\r\n\r\n<tr onMouseOver = \"this.bgColor = '#99ccff'\"\r\n    	onMouseOut = \"this.bgColor = '#FFFFcc'\">\r\n				<td width=\"4%\" style=\"border-style:solid; border-width:1px; \" bordercolor=\"#3399FF\">\r\n				<p align=\"center\">\r\n				<font face=\"Arial\"><span style=\"font-size: 10pt\">\r\n				<font color=\"#FFC36B\" size=\"3\">\r\n				<input type=\"radio\" value=".toCharArray();
    _jsp_string19 = " selected>".toCharArray();
    _jsp_string40 = "\r\n<p></p>\r\n\r\n\r\n".toCharArray();
    _jsp_string5 = "\");\r\n	}\r\n}\r\n\r\nfunction Add(form,field) \r\n{ \r\n	form.action=\"Nomination_AssignTR.jsp?add=1\";\r\n	form.method=\"post\";\r\n	form.submit();\r\n}\r\n//var flag = false;	\r\nfunction survey(form,field)\r\n{\r\n	if(check(field))\r\n	{\r\n		form.action=\"Nomination_AssignTR.jsp?survey=1\";\r\n		form.method=\"post\";\r\n		form.submit();\r\n	}\r\n	else\r\n	{\r\n		alert(\"".toCharArray();
    _jsp_string43 = "\r\n		<td align=\"center\" height=\"5\" valign=\"top\"><font size=\"1\" color=\"navy\" face=\"Arial\">&nbsp;&nbsp;<a style=\"TEXT-DECORATION: none; color:navy;\" href=\"Login.jsp\">Home</a>&nbsp;| <a color=\"navy\" face=\"Arial\">&nbsp;<a style=\"TEXT-DECORATION: none; color:navy;\" href=\"mailto:3SixtyAdmin@pcc.com.sg?subject=Regarding:\">Contact \r\n		Us</a><a color=\"navy\" face=\"Arial\" href=\"termofuse.jsp\" target=\"_blank\"><span style=\"color: #000080; text-decoration: none\"> | Terms of Use </span></a>| <span style=\"color: #000080; text-decoration: none\"><a style=\"TEXT-DECORATION: none; color:navy;\" href=\"http://www.pcc.com.sg/\" target=\"_blank\">PCC Website</a></span></font></td></tr><tr>\r\n		<font size=\"2\" face=\"Arial\" style=\"font-size: 14pt\" color=\"#000080\">\r\n   \r\n		<td align=\"center\" height=\"5\" valign=\"top\">\r\n		<font size=\"1\" color=\"navy\" face=\"Arial\">&nbsp;Copyright &copy; ".toCharArray();
    _jsp_string22 = "				\r\n\r\n				</select></span></font></td>\r\n\r\n		<td width=\"99\">\r\n<table border=\"0\" width=\"96%\" cellspacing=\"0\" cellpadding=\"0\">\r\n	<tr>\r\n		<font size=\"2\">\r\n   \r\n		<td width=\"71%\"> <font size=\"2\">\r\n   \r\n    	<input type=\"button\" value=\"".toCharArray();
    _jsp_string4 = "\r\n</head>\r\n<SCRIPT LANGUAGE=JAVASCRIPT>\r\n<!--\r\n// -->\r\n\r\nfunction check(field)\r\n{\r\n	var check= false;\r\n	\r\n	//Added by Xuehai, 27 May 2011. Verify if 'field' is null\r\n	if(field==null){\r\n		return check;\r\n	}\r\n	\r\n	for (i = 0; i < field.length; i++) \r\n	{\r\n		if(field[i].checked)\r\n			check = true;\r\n	}\r\n	if(field != null)\r\n	{\r\n		if(field.checked)\r\n		check = true;\r\n	}\r\n\r\n	return check;\r\n		\r\n}\r\nfunction AssignTarget(form,field)\r\n{\r\n	if(check(field))\r\n	{\r\n		form.action=\"Nomination_AssignTR.jsp?assign=1\";\r\n		form.method=\"post\";\r\n		form.submit();	 \r\n	}\r\n	else\r\n	{\r\n		alert(\"".toCharArray();
    _jsp_string16 = "\r\n\r\n<form name=\"Nomination\" action=\"Nomination_AssignTR.jsp\" method=\"post\">\r\n<table border=\"0\" width=\"610\" cellspacing=\"0\" cellpadding=\"0\">\r\n	<tr>\r\n				<td width=\"11%\">&nbsp;</td>\r\n				<td width=\"27%\">&nbsp;</td>\r\n				<td width=\"154\">\r\n				<p align=\"center\">\r\n				<font size=\"2\">\r\n   \r\n				<b><font face=\"Arial\" size=\"2\">".toCharArray();
    _jsp_string6 = "\");\r\n	}\r\n\r\n}\r\n\r\nfunction process(form,field)\r\n{\r\n	if(check(field))\r\n	{\r\n		form.action=\"Nomination_AssignTR.jsp?process=1\";\r\n		form.method=\"post\";\r\n		form.submit();\r\n	}\r\n	else\r\n	{\r\n		alert(\"".toCharArray();
    _jsp_string36 = "</td>\r\n     <td align=\"center\" style=\"border-style: solid; border-width: 1px\" bordercolor=\"#3399FF\"><font size=\"2\">".toCharArray();
    _jsp_string9 = "?\"))\r\n		{\r\n			form.action=\"Nomination_AssignTR.jsp?del=1\";\r\n			form.method=\"post\";\r\n			form.submit();	\r\n		}\r\n	}\r\n	else\r\n	{\r\n		alert(\"".toCharArray();
    _jsp_string24 = "</font></th>\r\n</table>\r\n\r\n  <div style='width:627px; height:201px; z-index:1; overflow:auto'>\r\n<table width=\"610\" border=\"1\" style='font-size:11.0pt;font-family:Arial' bordercolor=\"#3399FF\" bgcolor=\"#FFFFCC\">\r\n<tr>\r\n<th width=\"54%\" bgcolor=\"#000080\" style=\"border-right-style: none; border-right-width: medium\" colspan=\"2\"> \r\n   \r\n    	<b><font size=\"2\" style=\"color: white\"><a href=\"Nomination_AssignTR.jsp?sorting=1\"><font style='color:white'><u>".toCharArray();
    _jsp_string13 = "	\r\n	".toCharArray();
    _jsp_string21 = "			<option value=".toCharArray();
    _jsp_string42 = "\r\n\r\n<table border=\"0\" width=\"610\" height=\"26\" id=\"table1\">\r\n\r\n	<tr>\r\n		<font size=\"2\" face=\"Arial\" style=\"font-size: 14pt\" color=\"#000080\"/>\r\n		".toCharArray();
    _jsp_string28 = "</u></a></font></b></th>\r\n<th width=\"100\" bgcolor=\"#000080\"><b><font style='color:white' size=\"2\"><a href=\"Nomination_AssignTR.jsp?sorting=5\"><font style='color:white'><u>".toCharArray();
    _jsp_string34 = "</td>\r\n    <td align=\"center\" style=\"border-style: solid; border-width: 1px\" bordercolor=\"#3399FF\"><font size=\"2\">".toCharArray();
    _jsp_string14 = "\r\n	<script>\r\n	window.location = \"SurveyDetail.jsp\";\r\n</script>\r\n".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string1 = "                        \r\n".toCharArray();
    _jsp_string33 = "</td>\r\n				\r\n\r\n    <td align=\"center\" style=\"border-style:solid; border-width:1px; \" bordercolor=\"#3399FF\"><font size=\"2\">".toCharArray();
    _jsp_string27 = "</u></a></font></b></th>\r\n<th width=\"100\" bgcolor=\"#000080\"><b><font style='color:white' size=\"2\"><a href=\"Nomination_AssignTR.jsp?sorting=4\"><font style='color:white'><u>".toCharArray();
    _jsp_string20 = "</option>\r\n".toCharArray();
    _jsp_string10 = "\");\r\n	}\r\n\r\n}\r\n\r\n</SCRIPT>\r\n\r\n\r\n<body>\r\n".toCharArray();
    _jsp_string11 = " <font size=\"2\">\r\n   \r\n	<script>\r\n	parent.location.href = \"index.jsp\";\r\n	</script>\r\n".toCharArray();
    _jsp_string38 = "\r\n</table>\r\n</div>\r\n\r\n\r\n<table border=\"0\" width=\"610\" cellspacing=\"0\" cellpadding=\"0\">\r\n	<tr>\r\n		<td width=\"14%\">&nbsp;</td>\r\n		<td width=\"17%\">&nbsp;</td>\r\n		<td width=\"34%\">&nbsp;</td>\r\n		<td align=\"right\" colspan=\"2\">&nbsp;</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"14%\">&nbsp;\r\n		</td>\r\n		<td width=\"17%\">\r\n		<p align=\"center\">\r\n		</td>\r\n		<td width=\"34%\">\r\n		\r\n   \r\n		</td>\r\n		<td align=\"right\" width=\"22%\">\r\n		<font size=\"2\"><p align=\"center\"> \r\n		</td>\r\n		<td align=\"right\" width=\"9%\">\r\n		<font size=\"2\">\r\n   \r\n		<input type=\"button\" value=\"".toCharArray();
    _jsp_string15 = "	\r\n<script>	\r\n	window.open('CopySurvey.jsp','windowRef','scrollbars=no, width=300, height=300');\r\n</script>\r\n".toCharArray();
    _jsp_string26 = "</u></a></font></b></th>\r\n<th width=\"100\" bgcolor=\"#000080\"><b><font style='color:white' size=\"2\"><a href=\"Nomination_AssignTR.jsp?sorting=3\"><font style='color:white'><u>".toCharArray();
    _jsp_string30 = "</u></a></font></b></span></font></th>\r\n\r\n  ".toCharArray();
    _jsp_string41 = "\r\n\r\n".toCharArray();
  }
}
