/*
 * JSP generated by Resin Professional 4.0.36 (built Fri, 26 Apr 2013 03:33:09 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.text.DateFormat;
import java.util.*;
import java.util.Date;
import java.text.*;
import java.lang.String;
import CP_Classes.SurveyResult;
import CP_Classes.vo.votblSurvey;
import CP_Classes.vo.voUser;

public class _surveyresult__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");
    response.setCharacterEncoding("utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string1, 0, _jsp_string1.length);
     // Added by Roger 26 June 2008 
	//to check if any target is selected 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    CP_Classes.RatersDataEntry RDE;
    synchronized (pageContext.getSession()) {
      RDE = (CP_Classes.RatersDataEntry) pageContext.getSession().getAttribute("RDE");
      if (RDE == null) {
        RDE = new CP_Classes.RatersDataEntry();
        pageContext.getSession().setAttribute("RDE", RDE);
      }
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    CP_Classes.Create_Edit_Survey CE_Survey;
    synchronized (pageContext.getSession()) {
      CE_Survey = (CP_Classes.Create_Edit_Survey) pageContext.getSession().getAttribute("CE_Survey");
      if (CE_Survey == null) {
        CE_Survey = new CP_Classes.Create_Edit_Survey();
        pageContext.getSession().setAttribute("CE_Survey", CE_Survey);
      }
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    CP_Classes.SurveyResult SurveyResult;
    synchronized (pageContext.getSession()) {
      SurveyResult = (CP_Classes.SurveyResult) pageContext.getSession().getAttribute("SurveyResult");
      if (SurveyResult == null) {
        SurveyResult = new CP_Classes.SurveyResult();
        pageContext.getSession().setAttribute("SurveyResult", SurveyResult);
      }
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    CP_Classes.Calculation Calculation;
    synchronized (pageContext.getSession()) {
      Calculation = (CP_Classes.Calculation) pageContext.getSession().getAttribute("Calculation");
      if (Calculation == null) {
        Calculation = new CP_Classes.Calculation();
        pageContext.getSession().setAttribute("Calculation", Calculation);
      }
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    CP_Classes.User_Jenty User;
    synchronized (pageContext.getSession()) {
      User = (CP_Classes.User_Jenty) pageContext.getSession().getAttribute("User");
      if (User == null) {
        User = new CP_Classes.User_Jenty();
        pageContext.getSession().setAttribute("User", User);
      }
    }
    out.write(_jsp_string4, 0, _jsp_string4.length);
    CP_Classes.Login logchk;
    synchronized (pageContext.getSession()) {
      logchk = (CP_Classes.Login) pageContext.getSession().getAttribute("logchk");
      if (logchk == null) {
        logchk = new CP_Classes.Login();
        pageContext.getSession().setAttribute("logchk", logchk);
      }
    }
    out.write(_jsp_string4, 0, _jsp_string4.length);
    CP_Classes.Translate trans;
    synchronized (pageContext.getSession()) {
      trans = (CP_Classes.Translate) pageContext.getSession().getAttribute("trans");
      if (trans == null) {
        trans = new CP_Classes.Translate();
        pageContext.getSession().setAttribute("trans", trans);
      }
    }
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((trans.tslt("No record selected")));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((trans.tslt("No more rater can be added once the survey is closed")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((trans.tslt("Are you sure you want to re-open the Survery")));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    
String username=(String)session.getAttribute("username");

  if (!logchk.isUsable(username)) 
  { 

    out.write(_jsp_string9, 0, _jsp_string9.length);
      } 
  else 
  { 	
	int OrgID = logchk.getOrg();	
	int compID = logchk.getCompany();
	int pkUser = logchk.getPKUser();
	int userType = logchk.getUserType();	// 1= super admin
	int divID =  SurveyResult.getDivID();
	int deptID = SurveyResult.getDeptID();
	int groupID = SurveyResult.getGroupID();
	
	SimpleDateFormat day_view= new SimpleDateFormat ("dd/MM/yyyy");
	
	int surveyID = CE_Survey.getSurvey_ID();
	String strReliability = "";
	int nameSeq = User.NameSequence(OrgID);
	
	int reliability = Calculation.ReliabilityCheck(surveyID);
	if(reliability == 0)
		strReliability = "Trimmed Mean";
	else
		strReliability = "Reliability Index";
		
	votblSurvey SurveyInfo = SurveyResult.SurveyInfo(surveyID);
	
	String surveyName = SurveyInfo.getSurveyName();
	String dateOpened = day_view.format(SurveyInfo.getOpenedDate());
	
	String surveyLevel = "";
	int Level = Calculation.LevelOfSurvey(surveyID);
	if(Level == 0)
		surveyLevel = "Competency";
	else
		surveyLevel = "Key Behaviour";	
		
	String deadline = day_view.format(SurveyInfo.getDeadlineSubmissionDate());
	
	int surveyStatus = SurveyInfo.getSurveyStatus();
	String jobPost = RDE.getJobPosition(surveyID);

	SurveyResult.setSurveyID(surveyID);
	SurveyResult.setSurveyLevel(Level);
	
	
	//ResultSet groupSection = SurveyResult.GroupSection(surveyID);
	Vector targetID = new Vector();
	Vector raterID = new Vector();
	
	int target = 0, rater = 0;
	
	if(request.getParameter("btnSearch") != null) {
        groupID = Integer.parseInt(request.getParameter("lstGroup"));
		deptID = Integer.parseInt(request.getParameter("lstDepartment"));
		divID = Integer.parseInt(request.getParameter("selDiv"));

		SurveyResult.setGroupID(groupID);
		SurveyResult.setDeptID(deptID);
		SurveyResult.setDivID(divID);
		targetID = SurveyResult.TargetID(surveyID, divID, deptID, groupID);
	}else {
// ********* Edited by Tracy 11 Aug 08***************
// Show survey list upon page refreshing without having to click "Show" button
		//divID = -1;
		//deptID = -1;
		//groupID = -1;
		
		divID=0;
		deptID=0;
		groupID=0;
		
		SurveyResult.setDeptID(divID);
		SurveyResult.setDeptID(deptID);
		SurveyResult.setGroupID(groupID);
		targetID = SurveyResult.TargetID(surveyID, divID, deptID, groupID);
	}
// ****************************************************
	/**
         *Updated by Thant Thura Myo
         *
         **/
        if(request.getParameter("calculate")!=null){
            groupID = Integer.parseInt(request.getParameter("lstGroup"));
			deptID = Integer.parseInt(request.getParameter("lstDepartment"));
			divID = Integer.parseInt(request.getParameter("selDiv"));
	
			SurveyResult.setGroupID(groupID);
			SurveyResult.setDeptID(deptID);
			SurveyResult.setDivID(divID);   
			targetID = SurveyResult.TargetID(surveyID, divID, deptID, groupID);

        }
        
        /************************************************** ADDING TOGGLE FOR SORTING PURPOSE *************************************************/
        
        if(request.getParameter("sorting") != null)
		{	 //sorting , 
            int type = new Integer(request.getParameter("sorting")).intValue();
			int toggle = SurveyResult.getToggle();	//0=asc, 1=desc
			SurveyResult.setSortType(type);
			
			if(toggle == 0)
				toggle = 1;
			else
				toggle = 0;
				
			SurveyResult.setToggle(toggle);
			
			groupID = Integer.parseInt(request.getParameter("lstGroup"));
			deptID = Integer.parseInt(request.getParameter("lstDepartment"));
			divID = Integer.parseInt(request.getParameter("selDiv"));
	
			SurveyResult.setGroupID(groupID);
			SurveyResult.setDeptID(deptID);
			SurveyResult.setDivID(divID);
            targetID = SurveyResult.TargetID(surveyID, divID, deptID, groupID);
		} 
		else
		{
			CE_Survey.setSortType(1);
		}

    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((trans.tslt("Survey Name")));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((surveyName));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((trans.tslt("Date Opened")));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((dateOpened));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((trans.tslt("Level")));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((surveyLevel));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((trans.tslt("Deadline Submission")));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((deadline));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((trans.tslt("Job Position")));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((jobPost));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((trans.tslt("Reliability Check")));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((strReliability));
    out.write(_jsp_string21, 0, _jsp_string21.length);
     if (userType == 1 && surveyStatus == 2) {

    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((trans.tslt("Re-Open Survey")));
    out.write(_jsp_string23, 0, _jsp_string23.length);
     } else { 
    out.write(_jsp_string24, 0, _jsp_string24.length);
     } 
    out.write(_jsp_string25, 0, _jsp_string25.length);
     if(surveyStatus == 1) {

    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((trans.tslt("Close Survey")));
    out.write(_jsp_string27, 0, _jsp_string27.length);
     } else {

    out.write(_jsp_string24, 0, _jsp_string24.length);
     } 
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((trans.tslt("Process Result")));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((trans.tslt("To view a Target's result,click on the radio button next to the target.")));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((trans.tslt("To view a Rater's input, click on the radio button next to the rater")));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((trans.tslt("To calculate the scores for Target(s) prior to the completion of all raters, tick next to the target and click on the calculate button.")));
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print(( trans.tslt("Division") ));
    out.write(_jsp_string33, 0, _jsp_string33.length);
     		
		if(request.getParameter("div") != null)
		{
			if (request.getParameter("div").equals(""))
				divID = 0;
			else
				divID = Integer.parseInt(request.getParameter("div"));
		}
		if(divID == 0) {

    out.write(_jsp_string34, 0, _jsp_string34.length);
    
		} else {

    out.write(_jsp_string35, 0, _jsp_string35.length);
    
		}	  
	
	//Vector vDiv = SurveyResult.getvDiv();
	//if(vDiv.isEmpty())
	Vector vDiv = SurveyResult.getSurveyDiv(surveyID, logchk.getOrg());

	for(int i=0; i<vDiv.size(); i++) {
		String [] row = (String[])(vDiv.elementAt(i));
		int Division_ID = Integer.parseInt(row[0]);
		String Division_Desc = row[1];
	
	if(divID != 0 && divID == Division_ID)
	{
	
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((Division_ID));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print((Division_Desc));
    out.write(_jsp_string38, 0, _jsp_string38.length);
    	}else{
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((Division_ID));
    out.write('>');
    out.print((Division_Desc));
    out.write(_jsp_string38, 0, _jsp_string38.length);
    	}
}	


    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print(( trans.tslt("Department") ));
    out.write(_jsp_string40, 0, _jsp_string40.length);
     
   	if(request.getParameter("dept") != null)
	{
		if(request.getParameter("dept").length() > 0)
		{
   			deptID = Integer.parseInt(request.getParameter("dept"));
		}
	}
	
	if(deptID == 0) {

    out.write(_jsp_string41, 0, _jsp_string41.length);
    
		} else {

    out.write(_jsp_string42, 0, _jsp_string42.length);
    
}
	Vector vDept = SurveyResult.getvDept();
	
	if(vDept.isEmpty())
		vDept = SurveyResult.getSurveyDept(surveyID, divID);
		
	for(int i=0; i<vDept.size(); i++) {
		String [] row = (String[])(vDept.elementAt(i));
		int dep_ID = Integer.parseInt(row[0]);
		String dep_Name = row[1];
		
	if(deptID != 0 && deptID == dep_ID)
	{
	
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((dep_ID));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print((dep_Name));
    out.write(_jsp_string38, 0, _jsp_string38.length);
    	}else{
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((dep_ID));
    out.write('>');
    out.print((dep_Name));
    out.write(_jsp_string38, 0, _jsp_string38.length);
    	}
}	
    out.write(_jsp_string43, 0, _jsp_string43.length);
    out.print((trans.tslt("Group")));
    out.write(_jsp_string44, 0, _jsp_string44.length);
     
	if(request.getParameter("dept") != null)
	{
		if (request.getParameter("dept").equals(""))
			deptID = 0;
		else
			deptID = Integer.parseInt(request.getParameter("dept"));
	}
		
if(groupID == 0) {

    out.write(_jsp_string45, 0, _jsp_string45.length);
    
} else {

    out.write(_jsp_string46, 0, _jsp_string46.length);
    
}
	Vector vGroup = SurveyResult.getvGroup();
	String selectedGroupName = "";
	
	if(vGroup.isEmpty())
		vGroup = SurveyResult.getSurveyGroup(surveyID, deptID);
		
	for(int i=0; i<vGroup.size(); i++) {
		String [] row = (String[])(vGroup.elementAt(i));
		int Group_ID = Integer.parseInt(row[0]);
		String GroupName = row[1];
		
	if(groupID != 0 && groupID == Group_ID)
	{
		selectedGroupName = GroupName;
	
    out.write(_jsp_string47, 0, _jsp_string47.length);
    out.print((Group_ID));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print((GroupName));
    out.write(_jsp_string48, 0, _jsp_string48.length);
    	}else{
    out.write(_jsp_string47, 0, _jsp_string47.length);
    out.print((Group_ID));
    out.write('>');
    out.print((GroupName));
    out.write(_jsp_string48, 0, _jsp_string48.length);
    	}
}	
    out.write(_jsp_string49, 0, _jsp_string49.length);
    out.print((trans.tslt("Show") ));
    out.write(_jsp_string50, 0, _jsp_string50.length);
    
	String surveyImage = "";
	switch(surveyStatus) { 
		case 1 : surveyImage = "images/ViewSurveyOpen.bmp";
				 break;
		case 2 : surveyImage = "images/ViewSurveyClosed.bmp";
				 break;
		case 3 : surveyImage = "images/ViewSurveyClosed.bmp";
				 break;	
	}
	
	
    out.write(_jsp_string51, 0, _jsp_string51.length);
    out.print((surveyImage));
    out.write(_jsp_string52, 0, _jsp_string52.length);
    out.print((surveyName));
    out.write(_jsp_string53, 0, _jsp_string53.length);
    out.print((trans.tslt("Group") ));
    out.write(_jsp_string54, 0, _jsp_string54.length);
    out.print((trans.tslt("Target") ));
    out.write(_jsp_string55, 0, _jsp_string55.length);
    out.print((trans.tslt("Rater") ));
    out.write(_jsp_string56, 0, _jsp_string56.length);
    out.print((trans.tslt("Calculation Status") ));
    out.write(_jsp_string57, 0, _jsp_string57.length);
    
        
       
	SurveyResult.setSurveyID(surveyID);
        /*****************************
        * Updated by Thant Thura Myo 
        * Date 14 Jan 2008
        * Last Updated 11 mar 2008 by Thant Thura
        *******************************/
        
	 if(request.getParameter("calculate")!=null && request.getParameterValues("ckbTarget")!=null){
             
		 	SurveyResult SR = new SurveyResult();
            String []sTarget=request.getParameterValues("ckbTarget");
            
            boolean bResult=false;
            boolean bResult2=false;
            //Changed by Ha 17/06/08 to calculate and change the calculation and 
            //admin/system status  accordingly
            for(int i=0;i <sTarget.length; i++){
                 int iTarget=Integer.parseInt(sTarget[i]);
                 if (!SR.isAllRaterRated(surveyID, groupID, iTarget))                 
                 	bResult=SurveyResult.CalculateStatus(iTarget,surveyID, divID, deptID, groupID, 1);                 
                 else               
                	bResult=SurveyResult.CalculateStatus(iTarget,surveyID, divID, deptID, groupID, 0);
                 
                 
            }
            if(bResult){
                
    out.write(_jsp_string58, 0, _jsp_string58.length);
    out.print((trans.tslt("Calculation completed")));
    out.write(_jsp_string59, 0, _jsp_string59.length);
    	
            }
            else{
                   
    out.write(_jsp_string60, 0, _jsp_string60.length);
    out.print((trans.tslt("Calculation failed")));
    out.write(_jsp_string61, 0, _jsp_string61.length);
    	
            }
        }
	//if(groupID > 0) {
		int group = groupID;
		String groupName = selectedGroupName;
		
		if(targetID.size() != 0) {
		// Add by Santoso (2008-12-11)
		// avoid the same target printed twice by using a List which keep the already printed target
		List printedTargets = new ArrayList();
		for(int j=0; j<targetID.size(); j++) {
			voUser voUsr = (voUser)targetID.elementAt(j);
			target = voUsr.getTargetLoginID();
			// if target already printed, go to next target
			if (printedTargets.contains(new Integer(target))) {
				continue;
			} else {
				printedTargets.add(new Integer(target));
			}
			String givenName = voUsr.getGivenName();
			String familyName = voUsr.getFamilyName();
			
			String targetName = "";
			
			group = voUsr.getFKGroup();
			//0=familyname first
				if(nameSeq == 0)
					targetName = familyName + " " + givenName;
				else
					targetName = givenName + " " + familyName;
				if(j==0){
				
    out.write(_jsp_string62, 0, _jsp_string62.length);
    out.print(((targetID.size()+1)));
    out.write(_jsp_string63, 0, _jsp_string63.length);
    out.print((groupName));
    out.write(_jsp_string64, 0, _jsp_string64.length);
    
				
				}
				raterID = SurveyResult.RaterID(surveyID, group, target);
				boolean bIsAllRated =SurveyResult.isAllRated(surveyID, group, target);
				boolean bIsAllCalculated=SurveyResult.isAllCalculated(surveyID,group,target);
				int iNoRaterCalculated=SurveyResult.TotalRaterCalculated(surveyID,group,target);
				int iNoRaterCompleted=SurveyResult.TotalRaterCompleted(surveyID,group,target);

				if(bIsAllRated==false){
				
    out.write(_jsp_string65, 0, _jsp_string65.length);
    }
				else if(bIsAllRated==true&&bIsAllCalculated==true){
				
    out.write(_jsp_string66, 0, _jsp_string66.length);
    }
				else if(iNoRaterCalculated == iNoRaterCompleted){
				
    out.write(_jsp_string65, 0, _jsp_string65.length);
    
				 }else{
				String cName="chkTarget"+j;
				//System.out.println("Check Box Name : "+cName);
                  //              System.out.println("Check Box Value : "+target);
				
    out.write(_jsp_string67, 0, _jsp_string67.length);
    out.print((target));
    out.write(_jsp_string68, 0, _jsp_string68.length);
    }
    out.write(_jsp_string69, 0, _jsp_string69.length);
    out.print((target));
    out.write(_jsp_string70, 0, _jsp_string70.length);
    out.print((targetName));
    out.write(_jsp_string71, 0, _jsp_string71.length);
      
 		int iAdminStatus=-1;
		for(int k=0; k<raterID.size(); k++) {
			voUser voUsrRater = (voUser)raterID.elementAt(k);
			rater = voUsrRater.getRaterLoginID();
			
			String name [] = SurveyResult.RatersName(rater);
			
			givenName = name[0];
			familyName = name[1];
			
			String raterName = "";
			
			//0=familyname first
				if(nameSeq == 0)
					raterName = familyName + " " + givenName;
				else
					raterName = givenName + " " + familyName;
			
                                        
			int assignment = Calculation.AssignmentID(surveyID, target, rater);
			int status = SurveyResult.RatersStatus(assignment);
			int calculationStatus=SurveyResult.CalculationStatus(assignment);
			
			if(k==0){
				iAdminStatus=SurveyResult.AdminCalcStatus(assignment);
			}
			
			String image = "";
	String raterCode = SurveyResult.RaterCode(assignment);
	switch(status) {
		case 0 : image = "images/RaterIncomplete.bmp";
				 break;
		case 1 : image = "images/RaterCompleted.bmp";
				 break;
		case 2 : image = "images/RaterUnreliable.bmp";
				 break;
		case 3 : image = "images/RaterExcluded.bmp";
				 break;	
		//changed by Ha 16/06/08 filename should be RaterUnreliable.bmp
		case 4 : image = "images/RaterUnreliable.bmp";
				 break;	 
		//changed by Ha 01/07/08 add one more status: rater NA
		case 5 : image = "images/RaterNA.bmp";
				 break;
	}
	
			if(rater != 0) {
			
    out.write(_jsp_string72, 0, _jsp_string72.length);
    out.print((assignment));
    out.write(_jsp_string73, 0, _jsp_string73.length);
    out.print((image));
    out.write(_jsp_string52, 0, _jsp_string52.length);
    out.print((raterName + " (" + raterCode + ")"));
    out.write(_jsp_string74, 0, _jsp_string74.length);
    
			 if(calculationStatus!=0&&bIsAllCalculated==false){
    out.write(_jsp_string75, 0, _jsp_string75.length);
    }
    out.write(_jsp_string76, 0, _jsp_string76.length);
    }
 		}//End for Loop
 		
 		
    out.write(_jsp_string77, 0, _jsp_string77.length);
    
 				String sCalStatus="";
 				if(iAdminStatus==1){
 					sCalStatus="Admin Calc";
 				}else if(iAdminStatus==0){
 					sCalStatus="System Calc";
 				}
 				
 				if(iNoRaterCalculated == 0)
 					sCalStatus = "";
 				
    out.write(_jsp_string78, 0, _jsp_string78.length);
    out.print((sCalStatus));
    out.write(_jsp_string79, 0, _jsp_string79.length);
    
			}//End for Loop
		}//End if loop
	//}//End if loop
	
    out.write(_jsp_string80, 0, _jsp_string80.length);
     if (raterID.size()>0) { 
    out.write(_jsp_string81, 0, _jsp_string81.length);
     } 
    out.write(_jsp_string82, 0, _jsp_string82.length);
    // by lydia Date 05/09/2008 Fix jsp file to support Thai language 
    out.write(_jsp_string83, 0, _jsp_string83.length);
    
	Calendar c = Calendar.getInstance();
	int year = c.get(Calendar.YEAR);

    out.write(_jsp_string84, 0, _jsp_string84.length);
     // Denise 05/01/2010 update new email address 
    out.write(_jsp_string85, 0, _jsp_string85.length);
    out.print((year));
    out.write(_jsp_string86, 0, _jsp_string86.length);
    
	if(request.getParameter("close") != null) {
		Date today = new Date();
		SurveyResult.CloseSurvey(surveyID, pkUser, day_view.format(today));

    out.write(_jsp_string58, 0, _jsp_string58.length);
    out.print((trans.tslt("Survey has been closed")));
    out.write(_jsp_string59, 0, _jsp_string59.length);
    	
	} else if(request.getParameter("open") != null) {
		SurveyResult.OpenSurvey(surveyID, pkUser);

    out.write(_jsp_string58, 0, _jsp_string58.length);
    out.print((trans.tslt("Survey status has been set to Open")));
    out.write(_jsp_string87, 0, _jsp_string87.length);
    	
	}
			
	}

    out.write(_jsp_string88, 0, _jsp_string88.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7791540776389363938L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("SurveyResult.jsp"), -939764315427592024L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("Footer.jsp"), -1449263834919504582L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string66;
  private final static char []_jsp_string82;
  private final static char []_jsp_string29;
  private final static char []_jsp_string25;
  private final static char []_jsp_string10;
  private final static char []_jsp_string76;
  private final static char []_jsp_string36;
  private final static char []_jsp_string72;
  private final static char []_jsp_string65;
  private final static char []_jsp_string24;
  private final static char []_jsp_string54;
  private final static char []_jsp_string59;
  private final static char []_jsp_string6;
  private final static char []_jsp_string17;
  private final static char []_jsp_string46;
  private final static char []_jsp_string23;
  private final static char []_jsp_string9;
  private final static char []_jsp_string79;
  private final static char []_jsp_string81;
  private final static char []_jsp_string51;
  private final static char []_jsp_string50;
  private final static char []_jsp_string1;
  private final static char []_jsp_string56;
  private final static char []_jsp_string58;
  private final static char []_jsp_string88;
  private final static char []_jsp_string35;
  private final static char []_jsp_string63;
  private final static char []_jsp_string77;
  private final static char []_jsp_string13;
  private final static char []_jsp_string31;
  private final static char []_jsp_string78;
  private final static char []_jsp_string26;
  private final static char []_jsp_string52;
  private final static char []_jsp_string21;
  private final static char []_jsp_string28;
  private final static char []_jsp_string38;
  private final static char []_jsp_string18;
  private final static char []_jsp_string84;
  private final static char []_jsp_string71;
  private final static char []_jsp_string55;
  private final static char []_jsp_string43;
  private final static char []_jsp_string32;
  private final static char []_jsp_string7;
  private final static char []_jsp_string53;
  private final static char []_jsp_string70;
  private final static char []_jsp_string37;
  private final static char []_jsp_string47;
  private final static char []_jsp_string85;
  private final static char []_jsp_string69;
  private final static char []_jsp_string8;
  private final static char []_jsp_string5;
  private final static char []_jsp_string15;
  private final static char []_jsp_string12;
  private final static char []_jsp_string27;
  private final static char []_jsp_string20;
  private final static char []_jsp_string61;
  private final static char []_jsp_string22;
  private final static char []_jsp_string42;
  private final static char []_jsp_string80;
  private final static char []_jsp_string2;
  private final static char []_jsp_string75;
  private final static char []_jsp_string0;
  private final static char []_jsp_string45;
  private final static char []_jsp_string41;
  private final static char []_jsp_string33;
  private final static char []_jsp_string74;
  private final static char []_jsp_string86;
  private final static char []_jsp_string40;
  private final static char []_jsp_string16;
  private final static char []_jsp_string64;
  private final static char []_jsp_string60;
  private final static char []_jsp_string34;
  private final static char []_jsp_string11;
  private final static char []_jsp_string62;
  private final static char []_jsp_string73;
  private final static char []_jsp_string49;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string67;
  private final static char []_jsp_string48;
  private final static char []_jsp_string44;
  private final static char []_jsp_string19;
  private final static char []_jsp_string68;
  private final static char []_jsp_string57;
  private final static char []_jsp_string30;
  private final static char []_jsp_string39;
  private final static char []_jsp_string14;
  private final static char []_jsp_string87;
  private final static char []_jsp_string83;
  static {
    _jsp_string66 = "\r\n				<td>&nbsp;</td>\r\n\r\n				".toCharArray();
    _jsp_string82 = "</td>	</tr>\r\n  <p></p>\r\n\r\n\r\n".toCharArray();
    _jsp_string29 = " </font></td>\r\n	</tr>\r\n	<tr>\r\n		<td colspan=\"3\">\r\n		<ul>\r\n			<li><font face=\"Arial\" size=\"2\">\r\n			".toCharArray();
    _jsp_string25 = "\r\n  	<td>&nbsp;</td>\r\n  	<td>&nbsp;</td>\r\n	<td>&nbsp;</td>\r\n".toCharArray();
    _jsp_string10 = "\r\n\r\n<form action=\"SurveyResult.jsp\" method=\"post\" name=\"SurveyResult\">\r\n<table width=\"610\" border=\"0\" font style='font-size:10.0pt;font-family:Arial'>\r\n  <tr>\r\n    <td width=\"91\" height=\"24\" align=\"right\">".toCharArray();
    _jsp_string76 = "\r\n			 </td>\r\n    	</tr>\r\n 			".toCharArray();
    _jsp_string36 = "\r\n        <option value=".toCharArray();
    _jsp_string72 = "\r\n		<tr>			\r\n			 <td width=\"279\"><span class=\"style8\"><input name=\"survey\" type=\"radio\" value=\"".toCharArray();
    _jsp_string65 = "\r\n				<td>&nbsp;</td>\r\n				".toCharArray();
    _jsp_string24 = "\r\n<td>&nbsp;</td>\r\n".toCharArray();
    _jsp_string54 = "</font></td>\r\n	-->\r\n	<td width=\"19\" bgcolor=\"#000080\">\r\n	<input type=\"checkbox\" name=\"chkAll\" onClick=\"checkedAll(this.form, this.form.chkAll,this.form.ckbTarget)\" >\r\n	</td>\r\n\r\n	\r\n	<td width=\"190\" bgcolor=\"#000080\" align=\"center\"><b><font size=\"2\" style='color:white'><a href=\"javascript:sort(1)\"><font style='color:white'><u>".toCharArray();
    _jsp_string59 = "\");\r\n</script>\r\n\r\n".toCharArray();
    _jsp_string6 = "!\");\r\n	isValid = 0;\r\n	\r\n	return false;\r\n	//form.action = \"SurveyOptions.jsp?type=\" + type;\r\n	//form.submit();\r\n}\r\n\r\n//Edited by Xuehai 02 Jun 2011. Remove 'void'. Enable to run on different browers like Chrome&Firefox.\r\n//void function closeSurvey(form)\r\nfunction closeSurvey(form)\r\n{\r\n	if(confirm(\"".toCharArray();
    _jsp_string17 = " : </td>\r\n    <td>&nbsp;</td>\r\n    <td><input type=\"text\" name=\"deadline\" value=\"".toCharArray();
    _jsp_string46 = "\r\n<option value=0>All</option>\r\n".toCharArray();
    _jsp_string23 = "\" onClick=\"openSurvey(this.form)\"></td>\r\n".toCharArray();
    _jsp_string9 = "	<script>\r\n		parent.location.href = \"index.jsp\";\r\n	</script>\r\n".toCharArray();
    _jsp_string79 = "</td>\r\n				\r\n				\r\n							\r\n 				</tr>\r\n				".toCharArray();
    _jsp_string81 = "<input type=\"button\" name=\"btnCalculate\" value=\"Calculate\" onclick=\"confirmCalculate(this.form, this.form.ckbTarget)\"> ".toCharArray();
    _jsp_string51 = "\r\n	 \r\n   <p> <span class=\"style7\"><img src=".toCharArray();
    _jsp_string50 = "\"></td>\r\n    </tr>	\r\n  </table>\r\n<p><hr width=\"610\" align=\"left\"></p> \r\n<table width=\"609\" border=\"0\">\r\n	<tr>\r\n		<td>\r\n			<a href=\"javascript:onclick=openLegend()\"><font style='font-size:10.0pt;font-family:Arial'>Click here for Legend</font></a>\r\n		</td>\r\n	</tr>\r\n  <tr>\r\n    <td width=\"609\" valign=\"top\">\r\n	<table width=\"100%\" border=\"1\" align=\"left\" style='font-size:10.0pt;font-family:Arial' bordercolor=\"#3399FF\" bgcolor=\"#FFFFCC\">\r\n  	".toCharArray();
    _jsp_string1 = "\r\n<style type=\"text/css\">\r\n<!--\r\n.style1 {\r\n	color: #0066FF;\r\n	font-weight: bold;\r\n}\r\n.style7 {color: #000099; font-weight: bold; font-family: Arial;}\r\n.style8 {color: #000000}\r\n.style12 {\r\n	font-style: italic;\r\n	color: #FFFFFF;\r\n	font-weight: bold;\r\n	font-size: 10pt;\r\n}\r\n.style13 {\r\n	color: #003399;\r\n	border-left-style: solid;\r\n	border-left-width: 1px;\r\n	border-right-style: solid;\r\n	border-right-width: 1px;\r\n	border-bottom-style: solid;\r\n	border-bottom-width: 1px;\r\n}\r\n.style15 {color: #003399}\r\n-->\r\n</style>\r\n<script language=\"javascript\">\r\nfunction checkedAll(form, checkAll, field)\r\n{	\r\n	var alreadyCheck = 0;\r\n\r\n	if(field != null) {\r\n		\r\n		if(checkAll.checked == true) {\r\n			for(var i=0; i<field.length; i++) {\r\n				field[i].checked = true;\r\n				alreadyCheck == 1;\r\n			}\r\n			\r\n			if(alreadyCheck == 0)\r\n				field.checked = true;\r\n		}\r\n		else {\r\n			for(var i=0; i<field.length; i++) {\r\n				field[i].checked = false;	\r\n				alreadyCheck == 1;\r\n			}\r\n			\r\n			if(alreadyCheck == 0)\r\n				field.checked = false;\r\n				\r\n		}\r\n	\r\n	}\r\n}\r\n\r\nfunction confirmCalculate(form, field) {\r\n	".toCharArray();
    _jsp_string56 = "</font></b></td>\r\n	\r\n	<td width=\"80\" bgcolor=\"#000080\" align=\"center\"><b><font size=\"2\" style='color:white'><a href=\"javascript:sort(2)\"><font style='color:white'><u>".toCharArray();
    _jsp_string58 = "\r\n<script>\r\n	alert(\"".toCharArray();
    _jsp_string88 = "\r\n\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string35 = "			<option value=0>All</option>\r\n        ".toCharArray();
    _jsp_string63 = "\">\r\n   							<span class=\"style7\">&nbsp;".toCharArray();
    _jsp_string77 = "\r\n 				\r\n 				</table>\r\n 				</td>\r\n 				".toCharArray();
    _jsp_string13 = " : </td>\r\n    <td width=\"9\">&nbsp;</td>\r\n    <td width=\"156\"><input type=\"text\" name=\"dateOpened\" value=\"".toCharArray();
    _jsp_string31 = " </font></li>\r\n		</ul></td>\r\n	</tr>\r\n	<tr>\r\n		<td colspan=\"3\"><ul>\r\n			<li><font face=\"Arial\" size=\"2\">\r\n			".toCharArray();
    _jsp_string78 = "\r\n 				<td>&nbsp;".toCharArray();
    _jsp_string26 = "	  		\r\n	<td><input name=\"btnClose\" type=\"button\" value=\"".toCharArray();
    _jsp_string52 = ">     ".toCharArray();
    _jsp_string21 = "\" readonly></td>\r\n  </tr>\r\n  <tr>\r\n  	<td>&nbsp;</td>	  	\r\n	<td>&nbsp;</td>\r\n".toCharArray();
    _jsp_string28 = "\r\n  </tr>\r\n</table>\r\n<hr width=\"610\" align=\"left\">\r\n\r\n\r\n<table border=\"0\" width=\"610\" cellspacing=\"0\" cellpadding=\"0\" style='font-size:10.0pt;font-family:Arial'>\r\n	<tr>\r\n		<td colspan=\"3\">\r\n		<font face=\"Arial\" style=\"font-weight: 700\" color=\"#000080\" size=\"2\">".toCharArray();
    _jsp_string38 = "</option>\r\n        ".toCharArray();
    _jsp_string18 = "\" readonly></td>\r\n  </tr>  \r\n  <tr>\r\n    <td align=\"right\">".toCharArray();
    _jsp_string84 = "\r\n<script src=\"lib/js/bootstrap-button.js\"></script>\r\n<table border=\"0\" width=\"610\" height=\"26\" id=\"table1\">\r\n\r\n	<tr>\r\n		<font size=\"2\" face=\"Arial\" style=\"font-size: 14pt\" color=\"#000080\"/>\r\n		".toCharArray();
    _jsp_string71 = "</span></td>\r\n 				<td>\r\n 				<table border=\"0\" cellspacing=\"0\" cellpadding=0 >\r\n 		".toCharArray();
    _jsp_string55 = "</u></a></font></b></td>\r\n	\r\n	<td width=\"270\" bgcolor=\"#000080\" align=\"center\"><b><font size=\"2\" style='color:white'>".toCharArray();
    _jsp_string43 = "\r\n      </select></td>\r\n	</tr>\r\n	<tr>\r\n	  <td>&nbsp;</td>\r\n      <td>&nbsp;</td>\r\n      <td>&nbsp;</td>\r\n	</tr>\r\n	<tr>\r\n	  <td>".toCharArray();
    _jsp_string32 = " </font></li>\r\n		</ul></td>\r\n	</tr>\r\n\r\n	<tr>\r\n	  <td colspan=\"3\">&nbsp;</td>\r\n    </tr>\r\n	<tr>\r\n	  <td width=\"100\">".toCharArray();
    _jsp_string7 = "\")) {\r\n		form.action = \"SurveyResult.jsp?close=1\";\r\n		form.submit();\r\n	}\r\n}\r\n\r\n//void function openSurvey(form)\r\nfunction openSurvey(form)\r\n{\r\n	if(confirm(\"".toCharArray();
    _jsp_string53 = "</span></p>\r\n 	<tr height=\"20\">\r\n	<!--  commented off to remove \"Group\" column\r\n	<td width=50 bgcolor=\"#000080\">&nbsp;<font size=\"2\" style=\"color: white\">".toCharArray();
    _jsp_string70 = "\" onClick=\"surveyOption(this.form, this.form.survey, 2)\">&nbsp;".toCharArray();
    _jsp_string37 = " selected>".toCharArray();
    _jsp_string47 = "\r\n		<option value=".toCharArray();
    _jsp_string85 = "\r\n		<td align=\"center\" height=\"5\" valign=\"top\"><font size=\"1\" color=\"navy\" face=\"Arial\">&nbsp;&nbsp;<a style=\"TEXT-DECORATION: none; color:navy;\" href=\"Login.jsp\">Home</a>&nbsp;| <a color=\"navy\" face=\"Arial\">&nbsp;<a style=\"TEXT-DECORATION: none; color:navy;\" href=\"mailto:3SixtyAdmin@pcc.com.sg?subject=Regarding:\">Contact \r\n		Us</a><a color=\"navy\" face=\"Arial\" href=\"termofuse.jsp\" target=\"_blank\"><span style=\"color: #000080; text-decoration: none\"> | Terms of Use </span></a>| <span style=\"color: #000080; text-decoration: none\"><a style=\"TEXT-DECORATION: none; color:navy;\" href=\"http://www.pcc.com.sg/\" target=\"_blank\">PCC Website</a></span></font></td></tr><tr>\r\n		<font size=\"2\" face=\"Arial\" style=\"font-size: 14pt\" color=\"#000080\">\r\n   \r\n		<td align=\"center\" height=\"5\" valign=\"top\">\r\n		<font size=\"1\" color=\"navy\" face=\"Arial\">&nbsp;Copyright &copy; ".toCharArray();
    _jsp_string69 = "\r\n				<td><span class=\"style1\"><input name=\"survey\" type=\"radio\" value=\"".toCharArray();
    _jsp_string8 = "?\")) {\r\n		form.action = \"SurveyResult.jsp?open=1\";\r\n		form.submit();\r\n	}\r\n}\r\n\r\n//void function populateDept(form, field)\r\nfunction populateDept(form, field)\r\n{\r\n	form.action = \"SurveyResult.jsp?div=\" + field.value;\r\n	form.submit();\r\n}\r\n\r\n//void function populateGrp(form, field1, field2)\r\nfunction populateGrp(form, field1, field2)\r\n{\r\n	form.action = \"SurveyResult.jsp?div=\" + field1.value + \"&dept=\" + field2.value;\r\n	form.submit();\r\n}\r\n\r\n//void function openLegend(){\r\nfunction openLegend(){\r\n//Edited by Tracy, 08 Aug 08***********\r\n// Change the width of pop-up box\r\n	window.open(\"SurveyLegend.jsp\", \"Legend\", 'scrollbars=no, width=360, height=280');\r\n//**************************************\r\n}\r\n\r\n//void function sort( value ){\r\nfunction sort( value ){\r\n	this.SurveyResult.action = \"SurveyResult.jsp?sorting=\" + value;\r\n	this.SurveyResult.submit();\r\n}\r\n\r\n</script>\r\n\r\n".toCharArray();
    _jsp_string5 = "\r\n \r\n \r\n<script language=\"javascript\">\r\n\r\nvar x; \r\nvar y; \r\n\r\nfunction surveyOption(form, field, type)\r\n{\r\n	var isValid = 0;\r\n	var checkedValue = 0;\r\n	\r\n	//check which radio button clicked	\r\n	for (i = 0; i < field.length; i++) \r\n		if(field[i].checked) {\r\n			checkedValue = field[i].value;\r\n			//field[i].checked = false;\r\n			isValid = 1;\r\n		}\r\n	\r\n	if (isValid == 1)\r\n	{		\r\n		var myWindow, height, width;\r\n		\r\n		if(type == 2) {\r\n			height = 200;\r\n			width = 250;\r\n			x = parseInt(window.screen.width) / 2 - 125; \r\n			y = parseInt(window.screen.height) / 2 - 100;   \r\n		} else {\r\n			height = 150;\r\n			width = 350;\r\n			x = parseInt(window.screen.width) / 2 - 175; \r\n			y = parseInt(window.screen.height) / 2 - 75;   \r\n		}\r\n		myWindow=window.open('','windowRef','scrollbars=no, width=' + width + ', height=' + height);\r\n		myWindow.moveTo(x,y);\r\n		myWindow.location.href = 'SurveyOptions.jsp?type=' + type + \"&clicked=\" + checkedValue;\r\n	}\r\n	else\r\n		alert(\"".toCharArray();
    _jsp_string15 = " : </td>\r\n    <td>&nbsp;</td>\r\n    <td><input type=\"text\" name=\"surveyLevel\" value=\"".toCharArray();
    _jsp_string12 = "\" readonly>\r\n    </td>\r\n    <td width=\"9\">&nbsp;</td>\r\n    <td width=\"150\" align=\"right\">".toCharArray();
    _jsp_string27 = "\" onClick=\"closeSurvey(this.form)\"></td>\r\n".toCharArray();
    _jsp_string20 = " : </td>\r\n    <td>&nbsp;</td>\r\n    <td><input type=\"text\" name=\"reliability\" value=\"".toCharArray();
    _jsp_string61 = "\");\r\n        </script>\r\n\r\n".toCharArray();
    _jsp_string22 = "	\r\n  	<td><input name=\"btnOpen\" type=\"button\" value=\"".toCharArray();
    _jsp_string42 = "\r\n        <option value=0>All</option>\r\n        ".toCharArray();
    _jsp_string80 = "\r\n	\r\n	\r\n </table>\r\n\r\n</td>\r\n</tr>\r\n<tr><td align=right> ".toCharArray();
    _jsp_string2 = "\r\n	var hasError = true;\r\n	if (field.checked != undefined) {\r\n		hasError = !field.checked;\r\n	} else if (field.length != undefined) {\r\n		\r\n		if (field != null) {\r\n			for (i = 0; i < field.length; i++) {\r\n				if (field[i].checked) {				\r\n					hasError = false;\r\n					break;\r\n				}\r\n			}\r\n		} \r\n	}	\r\n	\r\n	if (hasError) {\r\n		alert(\"Please select a target\");\r\n		return;\r\n	}\r\n\r\n	if(confirm(\"Are you sure you want to proceed with the calculation process? This action will set the status to Admin Calc.\")) {\r\n		form.action=\"SurveyResult.jsp?calculate=1\";\r\n		form.method=\"post\";\r\n		form.submit();\r\n	}\r\n}\r\n\r\n	\r\n</script>\r\n</head>\r\n\r\n<body>\r\n".toCharArray();
    _jsp_string75 = "\r\n			 <img src=\"images/abacus.PNG\">\r\n			 ".toCharArray();
    _jsp_string0 = "  \r\n				 \r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>Survey Result</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n\r\n".toCharArray();
    _jsp_string45 = "\r\n<option value=0 selected>All</option>\r\n".toCharArray();
    _jsp_string41 = "\r\n        <option value=0 selected>All</option>\r\n        ".toCharArray();
    _jsp_string33 = "</td>\r\n      <td width=\"14\">:</td>\r\n      <td width=\"496\"><select name=\"selDiv\" onChange=\"populateDept(this.form, this.form.selDiv)\">\r\n".toCharArray();
    _jsp_string74 = "</span>\r\n			 ".toCharArray();
    _jsp_string86 = " Pacific Century Consulting Pte Ltd. All Rights Reserved.\r\n		</font>\r\n		</td>\r\n		\r\n	</tr>\r\n		\r\n</table>\r\n\r\n".toCharArray();
    _jsp_string40 = "</td>\r\n      <td width=\"14\">:</td>\r\n      <td width=\"496\"><select name=\"lstDepartment\" onChange=\"populateGrp(this.form, this.form.selDiv, this.form.lstDepartment)\">\r\n   ".toCharArray();
    _jsp_string16 = "\" readonly></td>\r\n    <td>&nbsp;</td>\r\n    <td align=\"right\">".toCharArray();
    _jsp_string64 = "</span></td>	\r\n					</tr> -->\r\n				<tr>\r\n				".toCharArray();
    _jsp_string60 = "\r\n        <script>\r\n	alert(\"".toCharArray();
    _jsp_string34 = "			<option value=0 selected>All</option>\r\n        ".toCharArray();
    _jsp_string11 = " : </td>\r\n    <td width=\"6\">&nbsp;</td>\r\n    <td width=\"159\">\r\n      <input type=\"text\" name=\"surveyName\" value=\"".toCharArray();
    _jsp_string62 = " \r\n					<!-- commented off due to the \"Group\" column being removed -->\r\n					<!-- <tr height=\"0\">\r\n   							<td rowspan=\"".toCharArray();
    _jsp_string73 = "\" onClick=\"surveyOption(this.form, this.form.survey, 3)\"><img src=".toCharArray();
    _jsp_string49 = "				  \r\n      </select></td>\r\n	</tr>\r\n	<tr>\r\n	  <td>&nbsp;</td>\r\n	  <td>&nbsp;</td>\r\n	  <td>&nbsp;</td>\r\n    </tr>\r\n	<tr>\r\n	  <td colspan=\"3\"><input type=\"submit\" name=\"btnSearch\" value=\"".toCharArray();
    _jsp_string4 = "  \r\n".toCharArray();
    _jsp_string3 = "\r\n".toCharArray();
    _jsp_string67 = "\r\n				<td ><input type=\"checkbox\" name=\"ckbTarget\" value=\"".toCharArray();
    _jsp_string48 = "</option>\r\n".toCharArray();
    _jsp_string44 = "</td>\r\n      <td>:</td>\r\n      <td><select name=\"lstGroup\">\r\n".toCharArray();
    _jsp_string19 = " : </td>\r\n    <td>&nbsp;</td>\r\n    <td><input type=\"text\" name=\"jobPost\" value=\"".toCharArray();
    _jsp_string68 = "\" /></td>\r\n				".toCharArray();
    _jsp_string57 = "</u></a></font></b></td>\r\n	\r\n</tr>\r\n	".toCharArray();
    _jsp_string30 = " </font></li>\r\n		</ul>\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td colspan=\"3\"><ul>\r\n			<li><font face=\"Arial\" size=\"2\">\r\n			".toCharArray();
    _jsp_string39 = "\r\n      </select></td>\r\n	</tr>\r\n	<tr>\r\n	  <td>&nbsp;</td>\r\n      <td>&nbsp;</td>\r\n      <td>&nbsp;</td>\r\n	</tr>\r\n	<tr>\r\n	  <td width=\"100\">".toCharArray();
    _jsp_string14 = "\" readonly></td>\r\n  </tr>\r\n  <tr>\r\n    <td height=\"26\" align=\"right\">".toCharArray();
    _jsp_string87 = " !\");\r\n</script>\r\n\r\n".toCharArray();
    _jsp_string83 = "\r\n\r\n".toCharArray();
  }
}
